.TH "colossal_cpp/imgui Directory Reference" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
colossal_cpp/imgui Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBfonts\fP"
.br
.ti -1c
.RI "directory \fBfreetype\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBimconfig\&.h\fP"
.br
.ti -1c
.RI "file \fBimgui\&.cpp\fP"
.br
.ti -1c
.RI "file \fBimgui\&.h\fP"
.br
.ti -1c
.RI "file \fBimgui_demo\&.cpp\fP"
.br
.ti -1c
.RI "file \fBimgui_draw\&.cpp\fP"
.br
.ti -1c
.RI "file \fBimgui_impl_glfw\&.cpp\fP"
.br
.ti -1c
.RI "file \fBimgui_impl_glfw\&.h\fP"
.br
.ti -1c
.RI "file \fBimgui_impl_opengl3\&.cpp\fP"
.br
.ti -1c
.RI "file \fBimgui_impl_opengl3\&.h\fP"
.br
.ti -1c
.RI "file \fBimgui_internal\&.h\fP"
.br
.ti -1c
.RI "file \fBimgui_tables\&.cpp\fP"
.br
.ti -1c
.RI "file \fBimgui_widgets\&.cpp\fP"
.br
.ti -1c
.RI "file \fBimstb_rectpack\&.h\fP"
.br
.ti -1c
.RI "file \fBimstb_textedit\&.h\fP"
.br
.ti -1c
.RI "file \fBimstb_truetype\&.h\fP"
.br
.in -1c
