.TH "cl_mb_device" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cl_mb_device
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <mb_device\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "char const  * \fBname\fP"
.br
.ti -1c
.RI "char * \fBip\fP"
.br
.RI "Used for TCP device\&. "
.ti -1c
.RI "int \fBport\fP"
.br
.RI "Used for TCP device\&. "
.ti -1c
.RI "char * \fBcom_port\fP"
.br
.RI "Used for serial device\&. "
.ti -1c
.RI "enum \fBcl_mb_device_baudrate\fP \fBbaudrate\fP"
.br
.RI "Used for serial device\&. "
.ti -1c
.RI "enum \fBcl_mb_device_parity\fP \fBparity\fP"
.br
.RI "Used for serial device\&. "
.ti -1c
.RI "enum \fBcl_mb_device_type\fP \fBdevice_type\fP"
.br
.RI "Used to select which device configuration to use\&. "
.ti -1c
.RI "char const  * \fBname_identifier\fP"
.br
.ti -1c
.RI "\fBcl_mb_channel\fP * \fBchannels\fP"
.br
.RI "A list of all the MB channels in the device\&. "
.ti -1c
.RI "size_t \fBchannel_count\fP"
.br
.RI "Keeps count of the number of channels\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBcl_mb_device\fP is the root type for the Modbus device\&. It holds all device configuration and channels data\&. 
.SH "Field Documentation"
.PP 
.SS "enum \fBcl_mb_device_baudrate\fP baudrate"

.PP
Used for serial device\&. 
.SS "size_t channel_count"

.PP
Keeps count of the number of channels\&. 
.SS "\fBcl_mb_channel\fP* channels"

.PP
A list of all the MB channels in the device\&. 
.SS "char* com_port"

.PP
Used for serial device\&. 
.SS "enum \fBcl_mb_device_type\fP device_type"

.PP
Used to select which device configuration to use\&. 
.SS "int id"

.SS "char* ip"

.PP
Used for TCP device\&. 
.SS "char const* name"

.SS "char const* name_identifier"
A special string that identifies the device in calculations \&.i\&.e "MB" or "AI"\&. 
.SS "enum \fBcl_mb_device_parity\fP parity"

.PP
Used for serial device\&. 
.SS "int port"

.PP
Used for TCP device\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
