.TH "colossal_cpp/colossal.h" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
colossal_cpp/colossal.h
.SH SYNOPSIS
.br
.PP
\fR#include <stdbool\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBcolossal\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBcolossal\fP \fBcolossal_t\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBcolossal\fP \fBcolossal_t\fP"
The colossal type is a singleton that holds all the imgui data\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
