.TH "colossal" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
colossal
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <colossal\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "bool \fBis_first_scan\fP"
.br
.RI "This is used as a switch to run some code at startup\&. "
.in -1c
.SH "Detailed Description"
.PP 
The colossal type is a singleton that holds all the imgui data\&. 
.SH "Field Documentation"
.PP 
.SS "int id"

.SS "bool is_first_scan"

.PP
This is used as a switch to run some code at startup\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
