.TH "ExampleMemberInfo" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExampleMemberInfo
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBName\fP"
.br
.ti -1c
.RI "\fBImGuiDataType\fP \fBDataType\fP"
.br
.ti -1c
.RI "int \fBDataCount\fP"
.br
.ti -1c
.RI "int \fBOffset\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int ExampleMemberInfo::DataCount"

.SS "\fBImGuiDataType\fP ExampleMemberInfo::DataType"

.SS "const char* ExampleMemberInfo::Name"

.SS "int ExampleMemberInfo::Offset"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
