.TH "ExampleAsset" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExampleAsset
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExampleAsset\fP (\fBImGuiID\fP id, int type)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBSortWithSortSpecs\fP (\fBImGuiTableSortSpecs\fP *sort_specs, \fBExampleAsset\fP *items, int items_count)"
.br
.ti -1c
.RI "static int \fBIMGUI_CDECL\fP \fBCompareWithSortSpecs\fP (const void *lhs, const void *rhs)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBImGuiID\fP \fBID\fP"
.br
.ti -1c
.RI "int \fBType\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const \fBImGuiTableSortSpecs\fP * \fBs_current_sort_specs\fP = NULL"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ExampleAsset::ExampleAsset (\fBImGuiID\fP id, int type)\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "static int \fBIMGUI_CDECL\fP ExampleAsset::CompareWithSortSpecs (const void * lhs, const void * rhs)\fR [inline]\fP, \fR [static]\fP"

.SS "static void ExampleAsset::SortWithSortSpecs (\fBImGuiTableSortSpecs\fP * sort_specs, \fBExampleAsset\fP * items, int items_count)\fR [inline]\fP, \fR [static]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBImGuiID\fP ExampleAsset::ID"

.SS "const \fBImGuiTableSortSpecs\fP * ExampleAsset::s_current_sort_specs = NULL\fR [static]\fP"

.SS "int ExampleAsset::Type"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
