.TH "ExampleAppPropertyEditor" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExampleAppPropertyEditor
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBDraw\fP (\fBExampleTreeNode\fP *root_node)"
.br
.ti -1c
.RI "void \fBDrawTreeNode\fP (\fBExampleTreeNode\fP *node)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBImGuiTextFilter\fP \fBFilter\fP"
.br
.ti -1c
.RI "\fBExampleTreeNode\fP * \fBVisibleNode\fP = NULL"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void ExampleAppPropertyEditor::Draw (\fBExampleTreeNode\fP * root_node)\fR [inline]\fP"

.SS "void ExampleAppPropertyEditor::DrawTreeNode (\fBExampleTreeNode\fP * node)\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBImGuiTextFilter\fP ExampleAppPropertyEditor::Filter"

.SS "\fBExampleTreeNode\fP* ExampleAppPropertyEditor::VisibleNode = NULL"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
