.TH "colossal_cpp/GLFW/glfw3native.h" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
colossal_cpp/GLFW/glfw3native.h \- The header of the native access functions\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
The header of the native access functions\&. 

This is the header file of the native access functions\&. See \fBNative access\fP for more information\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
