.TH "ImBitVector" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImBitVector
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imgui_internal\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBCreate\fP (int sz)"
.br
.ti -1c
.RI "void \fBClear\fP ()"
.br
.ti -1c
.RI "bool \fBTestBit\fP (int n) const"
.br
.ti -1c
.RI "void \fBSetBit\fP (int n)"
.br
.ti -1c
.RI "void \fBClearBit\fP (int n)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBImVector\fP< \fBImU32\fP > \fBStorage\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void ImBitVector::Clear ()\fR [inline]\fP"

.SS "void ImBitVector::ClearBit (int n)\fR [inline]\fP"

.SS "void ImBitVector::Create (int sz)\fR [inline]\fP"

.SS "void ImBitVector::SetBit (int n)\fR [inline]\fP"

.SS "bool ImBitVector::TestBit (int n) const\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBImVector\fP<\fBImU32\fP> ImBitVector::Storage"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
