.TH "ImDrawDataBuilder" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImDrawDataBuilder
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imgui_internal\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImDrawDataBuilder\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBImVector\fP< \fBImDrawList\fP * > * \fBLayers\fP [2]"
.br
.ti -1c
.RI "\fBImVector\fP< \fBImDrawList\fP * > \fBLayerData1\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ImDrawDataBuilder::ImDrawDataBuilder ()\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBImVector\fP<\fBImDrawList\fP*> ImDrawDataBuilder::LayerData1"

.SS "\fBImVector\fP<\fBImDrawList\fP*>* ImDrawDataBuilder::Layers[2]"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
