.TH "ImDrawCmdHeader" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImDrawCmdHeader
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imgui\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBImVec4\fP \fBClipRect\fP"
.br
.ti -1c
.RI "\fBImTextureID\fP \fBTextureId\fP"
.br
.ti -1c
.RI "unsigned int \fBVtxOffset\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBImVec4\fP ImDrawCmdHeader::ClipRect"

.SS "\fBImTextureID\fP ImDrawCmdHeader::TextureId"

.SS "unsigned int ImDrawCmdHeader::VtxOffset"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
