.TH "ImDrawCmd" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImDrawCmd
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imgui\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImDrawCmd\fP ()"
.br
.ti -1c
.RI "\fBImTextureID\fP \fBGetTexID\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBImVec4\fP \fBClipRect\fP"
.br
.ti -1c
.RI "\fBImTextureID\fP \fBTextureId\fP"
.br
.ti -1c
.RI "unsigned int \fBVtxOffset\fP"
.br
.ti -1c
.RI "unsigned int \fBIdxOffset\fP"
.br
.ti -1c
.RI "unsigned int \fBElemCount\fP"
.br
.ti -1c
.RI "\fBImDrawCallback\fP \fBUserCallback\fP"
.br
.ti -1c
.RI "void * \fBUserCallbackData\fP"
.br
.ti -1c
.RI "int \fBUserCallbackDataSize\fP"
.br
.ti -1c
.RI "int \fBUserCallbackDataOffset\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ImDrawCmd::ImDrawCmd ()\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBImTextureID\fP ImDrawCmd::GetTexID () const\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBImVec4\fP ImDrawCmd::ClipRect"

.SS "unsigned int ImDrawCmd::ElemCount"

.SS "unsigned int ImDrawCmd::IdxOffset"

.SS "\fBImTextureID\fP ImDrawCmd::TextureId"

.SS "\fBImDrawCallback\fP ImDrawCmd::UserCallback"

.SS "void* ImDrawCmd::UserCallbackData"

.SS "int ImDrawCmd::UserCallbackDataOffset"

.SS "int ImDrawCmd::UserCallbackDataSize"

.SS "unsigned int ImDrawCmd::VtxOffset"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
