.TH "ImDrawVert" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImDrawVert
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imgui\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBImVec2\fP \fBpos\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBuv\fP"
.br
.ti -1c
.RI "\fBImU32\fP \fBcol\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBImU32\fP ImDrawVert::col"

.SS "\fBImVec2\fP ImDrawVert::pos"

.SS "\fBImVec2\fP ImDrawVert::uv"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
