.TH "ImDrawChannel" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImDrawChannel
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imgui\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBImVector\fP< \fBImDrawCmd\fP > \fB_CmdBuffer\fP"
.br
.ti -1c
.RI "\fBImVector\fP< \fBImDrawIdx\fP > \fB_IdxBuffer\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBImVector\fP<\fBImDrawCmd\fP> ImDrawChannel::_CmdBuffer"

.SS "\fBImVector\fP<\fBImDrawIdx\fP> ImDrawChannel::_IdxBuffer"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
