.TH "ImFontBuildSrcData" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImFontBuildSrcData
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBstbtt_fontinfo\fP \fBFontInfo\fP"
.br
.ti -1c
.RI "\fBstbtt_pack_range\fP \fBPackRange\fP"
.br
.ti -1c
.RI "\fBstbrp_rect\fP * \fBRects\fP"
.br
.ti -1c
.RI "\fBstbtt_packedchar\fP * \fBPackedChars\fP"
.br
.ti -1c
.RI "const \fBImWchar\fP * \fBSrcRanges\fP"
.br
.ti -1c
.RI "int \fBDstIndex\fP"
.br
.ti -1c
.RI "int \fBGlyphsHighest\fP"
.br
.ti -1c
.RI "int \fBGlyphsCount\fP"
.br
.ti -1c
.RI "\fBImBitVector\fP \fBGlyphsSet\fP"
.br
.ti -1c
.RI "\fBImVector\fP< int > \fBGlyphsList\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int ImFontBuildSrcData::DstIndex"

.SS "\fBstbtt_fontinfo\fP ImFontBuildSrcData::FontInfo"

.SS "int ImFontBuildSrcData::GlyphsCount"

.SS "int ImFontBuildSrcData::GlyphsHighest"

.SS "\fBImVector\fP<int> ImFontBuildSrcData::GlyphsList"

.SS "\fBImBitVector\fP ImFontBuildSrcData::GlyphsSet"

.SS "\fBstbtt_packedchar\fP* ImFontBuildSrcData::PackedChars"

.SS "\fBstbtt_pack_range\fP ImFontBuildSrcData::PackRange"

.SS "\fBstbrp_rect\fP* ImFontBuildSrcData::Rects"

.SS "const \fBImWchar\fP* ImFontBuildSrcData::SrcRanges"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
