.TH "ImFontAtlasCustomRect" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImFontAtlasCustomRect
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imgui\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImFontAtlasCustomRect\fP ()"
.br
.ti -1c
.RI "bool \fBIsPacked\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned short \fBX\fP"
.br
.ti -1c
.RI "unsigned short \fBY\fP"
.br
.ti -1c
.RI "unsigned short \fBWidth\fP"
.br
.ti -1c
.RI "unsigned short \fBHeight\fP"
.br
.ti -1c
.RI "unsigned int \fBGlyphID\fP: 31"
.br
.ti -1c
.RI "unsigned int \fBGlyphColored\fP: 1"
.br
.ti -1c
.RI "float \fBGlyphAdvanceX\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBGlyphOffset\fP"
.br
.ti -1c
.RI "\fBImFont\fP * \fBFont\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ImFontAtlasCustomRect::ImFontAtlasCustomRect ()\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool ImFontAtlasCustomRect::IsPacked () const\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBImFont\fP* ImFontAtlasCustomRect::Font"

.SS "float ImFontAtlasCustomRect::GlyphAdvanceX"

.SS "unsigned int ImFontAtlasCustomRect::GlyphColored"

.SS "unsigned int ImFontAtlasCustomRect::GlyphID"

.SS "\fBImVec2\fP ImFontAtlasCustomRect::GlyphOffset"

.SS "unsigned short ImFontAtlasCustomRect::Height"

.SS "unsigned short ImFontAtlasCustomRect::Width"

.SS "unsigned short ImFontAtlasCustomRect::X"

.SS "unsigned short ImFontAtlasCustomRect::Y"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
