.TH "ImFontBuildDstData" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImFontBuildDstData
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBSrcCount\fP"
.br
.ti -1c
.RI "int \fBGlyphsHighest\fP"
.br
.ti -1c
.RI "int \fBGlyphsCount\fP"
.br
.ti -1c
.RI "\fBImBitVector\fP \fBGlyphsSet\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int ImFontBuildDstData::GlyphsCount"

.SS "int ImFontBuildDstData::GlyphsHighest"

.SS "\fBImBitVector\fP ImFontBuildDstData::GlyphsSet"

.SS "int ImFontBuildDstData::SrcCount"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
