.TH "ImFontBuildSrcGlyphFT" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImFontBuildSrcGlyphFT
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImFontBuildSrcGlyphFT\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GlyphInfo \fBInfo\fP"
.br
.ti -1c
.RI "uint32_t \fBCodepoint\fP"
.br
.ti -1c
.RI "unsigned int * \fBBitmapData\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ImFontBuildSrcGlyphFT::ImFontBuildSrcGlyphFT ()\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "unsigned int* ImFontBuildSrcGlyphFT::BitmapData"

.SS "uint32_t ImFontBuildSrcGlyphFT::Codepoint"

.SS "GlyphInfo ImFontBuildSrcGlyphFT::Info"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
