.TH "ImFontGlyph" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImFontGlyph
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imgui\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned int \fBColored\fP: 1"
.br
.ti -1c
.RI "unsigned int \fBVisible\fP: 1"
.br
.ti -1c
.RI "unsigned int \fBCodepoint\fP: 30"
.br
.ti -1c
.RI "float \fBAdvanceX\fP"
.br
.ti -1c
.RI "float \fBX0\fP"
.br
.ti -1c
.RI "float \fBY0\fP"
.br
.ti -1c
.RI "float \fBX1\fP"
.br
.ti -1c
.RI "float \fBY1\fP"
.br
.ti -1c
.RI "float \fBU0\fP"
.br
.ti -1c
.RI "float \fBV0\fP"
.br
.ti -1c
.RI "float \fBU1\fP"
.br
.ti -1c
.RI "float \fBV1\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "float ImFontGlyph::AdvanceX"

.SS "unsigned int ImFontGlyph::Codepoint"

.SS "unsigned int ImFontGlyph::Colored"

.SS "float ImFontGlyph::U0"

.SS "float ImFontGlyph::U1"

.SS "float ImFontGlyph::V0"

.SS "float ImFontGlyph::V1"

.SS "unsigned int ImFontGlyph::Visible"

.SS "float ImFontGlyph::X0"

.SS "float ImFontGlyph::X1"

.SS "float ImFontGlyph::Y0"

.SS "float ImFontGlyph::Y1"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
