.TH "ImFontConfig" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImFontConfig
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imgui\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIMGUI_API\fP \fBImFontConfig\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void * \fBFontData\fP"
.br
.ti -1c
.RI "int \fBFontDataSize\fP"
.br
.ti -1c
.RI "bool \fBFontDataOwnedByAtlas\fP"
.br
.ti -1c
.RI "bool \fBMergeMode\fP"
.br
.ti -1c
.RI "bool \fBPixelSnapH\fP"
.br
.ti -1c
.RI "int \fBFontNo\fP"
.br
.ti -1c
.RI "int \fBOversampleH\fP"
.br
.ti -1c
.RI "int \fBOversampleV\fP"
.br
.ti -1c
.RI "float \fBSizePixels\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBGlyphOffset\fP"
.br
.ti -1c
.RI "const \fBImWchar\fP * \fBGlyphRanges\fP"
.br
.ti -1c
.RI "float \fBGlyphMinAdvanceX\fP"
.br
.ti -1c
.RI "float \fBGlyphMaxAdvanceX\fP"
.br
.ti -1c
.RI "float \fBGlyphExtraAdvanceX\fP"
.br
.ti -1c
.RI "unsigned int \fBFontBuilderFlags\fP"
.br
.ti -1c
.RI "float \fBRasterizerMultiply\fP"
.br
.ti -1c
.RI "float \fBRasterizerDensity\fP"
.br
.ti -1c
.RI "\fBImWchar\fP \fBEllipsisChar\fP"
.br
.ti -1c
.RI "char \fBName\fP [40]"
.br
.ti -1c
.RI "\fBImFont\fP * \fBDstFont\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ImFontConfig::ImFontConfig ()"

.SH "Member Data Documentation"
.PP 
.SS "\fBImFont\fP* ImFontConfig::DstFont"

.SS "\fBImWchar\fP ImFontConfig::EllipsisChar"

.SS "unsigned int ImFontConfig::FontBuilderFlags"

.SS "void* ImFontConfig::FontData"

.SS "bool ImFontConfig::FontDataOwnedByAtlas"

.SS "int ImFontConfig::FontDataSize"

.SS "int ImFontConfig::FontNo"

.SS "float ImFontConfig::GlyphExtraAdvanceX"

.SS "float ImFontConfig::GlyphMaxAdvanceX"

.SS "float ImFontConfig::GlyphMinAdvanceX"

.SS "\fBImVec2\fP ImFontConfig::GlyphOffset"

.SS "const \fBImWchar\fP* ImFontConfig::GlyphRanges"

.SS "bool ImFontConfig::MergeMode"

.SS "char ImFontConfig::Name[40]"

.SS "int ImFontConfig::OversampleH"

.SS "int ImFontConfig::OversampleV"

.SS "bool ImFontConfig::PixelSnapH"

.SS "float ImFontConfig::RasterizerDensity"

.SS "float ImFontConfig::RasterizerMultiply"

.SS "float ImFontConfig::SizePixels"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
