.TH "ImFontBuildSrcDataFT" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImFontBuildSrcDataFT
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FreeTypeFont \fBFont\fP"
.br
.ti -1c
.RI "\fBstbrp_rect\fP * \fBRects\fP"
.br
.ti -1c
.RI "const \fBImWchar\fP * \fBSrcRanges\fP"
.br
.ti -1c
.RI "int \fBDstIndex\fP"
.br
.ti -1c
.RI "int \fBGlyphsHighest\fP"
.br
.ti -1c
.RI "int \fBGlyphsCount\fP"
.br
.ti -1c
.RI "\fBImBitVector\fP \fBGlyphsSet\fP"
.br
.ti -1c
.RI "\fBImVector\fP< \fBImFontBuildSrcGlyphFT\fP > \fBGlyphsList\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int ImFontBuildSrcDataFT::DstIndex"

.SS "FreeTypeFont ImFontBuildSrcDataFT::Font"

.SS "int ImFontBuildSrcDataFT::GlyphsCount"

.SS "int ImFontBuildSrcDataFT::GlyphsHighest"

.SS "\fBImVector\fP<\fBImFontBuildSrcGlyphFT\fP> ImFontBuildSrcDataFT::GlyphsList"

.SS "\fBImBitVector\fP ImFontBuildSrcDataFT::GlyphsSet"

.SS "\fBstbrp_rect\fP* ImFontBuildSrcDataFT::Rects"

.SS "const \fBImWchar\fP* ImFontBuildSrcDataFT::SrcRanges"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
