.TH "ImGuiTableColumnSortSpecs" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiTableColumnSortSpecs
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imgui\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImGuiTableColumnSortSpecs\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBImGuiID\fP \fBColumnUserID\fP"
.br
.ti -1c
.RI "\fBImS16\fP \fBColumnIndex\fP"
.br
.ti -1c
.RI "\fBImS16\fP \fBSortOrder\fP"
.br
.ti -1c
.RI "\fBImGuiSortDirection\fP \fBSortDirection\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ImGuiTableColumnSortSpecs::ImGuiTableColumnSortSpecs ()\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBImS16\fP ImGuiTableColumnSortSpecs::ColumnIndex"

.SS "\fBImGuiID\fP ImGuiTableColumnSortSpecs::ColumnUserID"

.SS "\fBImGuiSortDirection\fP ImGuiTableColumnSortSpecs::SortDirection"

.SS "\fBImS16\fP ImGuiTableColumnSortSpecs::SortOrder"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
