.TH "ImGuiDeactivatedItemData" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiDeactivatedItemData
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imgui_internal\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBImGuiID\fP \fBID\fP"
.br
.ti -1c
.RI "int \fBElapseFrame\fP"
.br
.ti -1c
.RI "bool \fBHasBeenEditedBefore\fP"
.br
.ti -1c
.RI "bool \fBIsAlive\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int ImGuiDeactivatedItemData::ElapseFrame"

.SS "bool ImGuiDeactivatedItemData::HasBeenEditedBefore"

.SS "\fBImGuiID\fP ImGuiDeactivatedItemData::ID"

.SS "bool ImGuiDeactivatedItemData::IsAlive"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
