.TH "ImGuiIDStackTool" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiIDStackTool
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imgui_internal\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImGuiIDStackTool\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBLastActiveFrame\fP"
.br
.ti -1c
.RI "int \fBStackLevel\fP"
.br
.ti -1c
.RI "\fBImGuiID\fP \fBQueryId\fP"
.br
.ti -1c
.RI "\fBImVector\fP< \fBImGuiStackLevelInfo\fP > \fBResults\fP"
.br
.ti -1c
.RI "bool \fBCopyToClipboardOnCtrlC\fP"
.br
.ti -1c
.RI "float \fBCopyToClipboardLastTime\fP"
.br
.ti -1c
.RI "\fBImGuiTextBuffer\fP \fBResultPathBuf\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ImGuiIDStackTool::ImGuiIDStackTool ()\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "float ImGuiIDStackTool::CopyToClipboardLastTime"

.SS "bool ImGuiIDStackTool::CopyToClipboardOnCtrlC"

.SS "int ImGuiIDStackTool::LastActiveFrame"

.SS "\fBImGuiID\fP ImGuiIDStackTool::QueryId"

.SS "\fBImGuiTextBuffer\fP ImGuiIDStackTool::ResultPathBuf"

.SS "\fBImVector\fP<\fBImGuiStackLevelInfo\fP> ImGuiIDStackTool::Results"

.SS "int ImGuiIDStackTool::StackLevel"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
