.TH "ImGuiListClipperData" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiListClipperData
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imgui_internal\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImGuiListClipperData\fP ()"
.br
.ti -1c
.RI "void \fBReset\fP (\fBImGuiListClipper\fP *clipper)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBImGuiListClipper\fP * \fBListClipper\fP"
.br
.ti -1c
.RI "float \fBLossynessOffset\fP"
.br
.ti -1c
.RI "int \fBStepNo\fP"
.br
.ti -1c
.RI "int \fBItemsFrozen\fP"
.br
.ti -1c
.RI "\fBImVector\fP< \fBImGuiListClipperRange\fP > \fBRanges\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ImGuiListClipperData::ImGuiListClipperData ()\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void ImGuiListClipperData::Reset (\fBImGuiListClipper\fP * clipper)\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "int ImGuiListClipperData::ItemsFrozen"

.SS "\fBImGuiListClipper\fP* ImGuiListClipperData::ListClipper"

.SS "float ImGuiListClipperData::LossynessOffset"

.SS "\fBImVector\fP<\fBImGuiListClipperRange\fP> ImGuiListClipperData::Ranges"

.SS "int ImGuiListClipperData::StepNo"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
