.TH "ImGuiGroupData" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiGroupData
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imgui_internal\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBImGuiID\fP \fBWindowID\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBBackupCursorPos\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBBackupCursorMaxPos\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBBackupCursorPosPrevLine\fP"
.br
.ti -1c
.RI "\fBImVec1\fP \fBBackupIndent\fP"
.br
.ti -1c
.RI "\fBImVec1\fP \fBBackupGroupOffset\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBBackupCurrLineSize\fP"
.br
.ti -1c
.RI "float \fBBackupCurrLineTextBaseOffset\fP"
.br
.ti -1c
.RI "\fBImGuiID\fP \fBBackupActiveIdIsAlive\fP"
.br
.ti -1c
.RI "bool \fBBackupDeactivatedIdIsAlive\fP"
.br
.ti -1c
.RI "bool \fBBackupHoveredIdIsAlive\fP"
.br
.ti -1c
.RI "bool \fBBackupIsSameLine\fP"
.br
.ti -1c
.RI "bool \fBEmitItem\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBImGuiID\fP ImGuiGroupData::BackupActiveIdIsAlive"

.SS "\fBImVec2\fP ImGuiGroupData::BackupCurrLineSize"

.SS "float ImGuiGroupData::BackupCurrLineTextBaseOffset"

.SS "\fBImVec2\fP ImGuiGroupData::BackupCursorMaxPos"

.SS "\fBImVec2\fP ImGuiGroupData::BackupCursorPos"

.SS "\fBImVec2\fP ImGuiGroupData::BackupCursorPosPrevLine"

.SS "bool ImGuiGroupData::BackupDeactivatedIdIsAlive"

.SS "\fBImVec1\fP ImGuiGroupData::BackupGroupOffset"

.SS "bool ImGuiGroupData::BackupHoveredIdIsAlive"

.SS "\fBImVec1\fP ImGuiGroupData::BackupIndent"

.SS "bool ImGuiGroupData::BackupIsSameLine"

.SS "bool ImGuiGroupData::EmitItem"

.SS "\fBImGuiID\fP ImGuiGroupData::WindowID"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
