.TH "ImGuiColorMod" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiColorMod
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imgui_internal\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBImGuiCol\fP \fBCol\fP"
.br
.ti -1c
.RI "\fBImVec4\fP \fBBackupValue\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBImVec4\fP ImGuiColorMod::BackupValue"

.SS "\fBImGuiCol\fP ImGuiColorMod::Col"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
