.TH "colossal_cpp/imgui/imgui_impl_opengl3.h" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
colossal_cpp/imgui/imgui_impl_opengl3.h
.SH SYNOPSIS
.br
.PP
\fR#include 'imgui\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBIMGUI_IMPL_API\fP bool \fBImGui_ImplOpenGL3_Init\fP (const char *glsl_version=nullptr)"
.br
.ti -1c
.RI "\fBIMGUI_IMPL_API\fP void \fBImGui_ImplOpenGL3_Shutdown\fP ()"
.br
.ti -1c
.RI "\fBIMGUI_IMPL_API\fP void \fBImGui_ImplOpenGL3_NewFrame\fP ()"
.br
.ti -1c
.RI "\fBIMGUI_IMPL_API\fP void \fBImGui_ImplOpenGL3_RenderDrawData\fP (\fBImDrawData\fP *draw_data)"
.br
.ti -1c
.RI "\fBIMGUI_IMPL_API\fP bool \fBImGui_ImplOpenGL3_CreateFontsTexture\fP ()"
.br
.ti -1c
.RI "\fBIMGUI_IMPL_API\fP void \fBImGui_ImplOpenGL3_DestroyFontsTexture\fP ()"
.br
.ti -1c
.RI "\fBIMGUI_IMPL_API\fP bool \fBImGui_ImplOpenGL3_CreateDeviceObjects\fP ()"
.br
.ti -1c
.RI "\fBIMGUI_IMPL_API\fP void \fBImGui_ImplOpenGL3_DestroyDeviceObjects\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBIMGUI_IMPL_API\fP bool ImGui_ImplOpenGL3_CreateDeviceObjects ()"

.SS "\fBIMGUI_IMPL_API\fP bool ImGui_ImplOpenGL3_CreateFontsTexture ()"

.SS "\fBIMGUI_IMPL_API\fP void ImGui_ImplOpenGL3_DestroyDeviceObjects ()"

.SS "\fBIMGUI_IMPL_API\fP void ImGui_ImplOpenGL3_DestroyFontsTexture ()"

.SS "\fBIMGUI_IMPL_API\fP bool ImGui_ImplOpenGL3_Init (const char * glsl_version = \fRnullptr\fP)"

.SS "\fBIMGUI_IMPL_API\fP void ImGui_ImplOpenGL3_NewFrame ()"

.SS "\fBIMGUI_IMPL_API\fP void ImGui_ImplOpenGL3_RenderDrawData (\fBImDrawData\fP * draw_data)"

.SS "\fBIMGUI_IMPL_API\fP void ImGui_ImplOpenGL3_Shutdown ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
