.TH "ImGuiDebugAllocEntry" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiDebugAllocEntry
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imgui_internal\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBFrameCount\fP"
.br
.ti -1c
.RI "\fBImS16\fP \fBAllocCount\fP"
.br
.ti -1c
.RI "\fBImS16\fP \fBFreeCount\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBImS16\fP ImGuiDebugAllocEntry::AllocCount"

.SS "int ImGuiDebugAllocEntry::FrameCount"

.SS "\fBImS16\fP ImGuiDebugAllocEntry::FreeCount"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
