.TH "ImGuiInputEventMouseWheel" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiInputEventMouseWheel
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imgui_internal\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBWheelX\fP"
.br
.ti -1c
.RI "float \fBWheelY\fP"
.br
.ti -1c
.RI "\fBImGuiMouseSource\fP \fBMouseSource\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBImGuiMouseSource\fP ImGuiInputEventMouseWheel::MouseSource"

.SS "float ImGuiInputEventMouseWheel::WheelX"

.SS "float ImGuiInputEventMouseWheel::WheelY"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
