.TH "ImGuiFreeType" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiFreeType
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBIMGUI_API\fP const \fBImFontBuilderIO\fP * \fBGetBuilderForFreeType\fP ()"
.br
.ti -1c
.RI "\fBIMGUI_API\fP void \fBSetAllocatorFunctions\fP (void *(*alloc_func)(size_t sz, void *user_data), void(*free_func)(void *ptr, void *user_data), void *user_data=nullptr)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "const \fBImFontBuilderIO\fP * ImGuiFreeType::GetBuilderForFreeType ()"

.SS "void ImGuiFreeType::SetAllocatorFunctions (void *(* alloc_func )(size_t sz, void *user_data), void(* free_func )(void *ptr, void *user_data), void * user_data = \fRnullptr\fP)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
