.TH "ImGuiNavItemData" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiNavItemData
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imgui_internal\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImGuiNavItemData\fP ()"
.br
.ti -1c
.RI "void \fBClear\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBImGuiWindow\fP * \fBWindow\fP"
.br
.ti -1c
.RI "\fBImGuiID\fP \fBID\fP"
.br
.ti -1c
.RI "\fBImGuiID\fP \fBFocusScopeId\fP"
.br
.ti -1c
.RI "\fBImRect\fP \fBRectRel\fP"
.br
.ti -1c
.RI "\fBImGuiItemFlags\fP \fBItemFlags\fP"
.br
.ti -1c
.RI "float \fBDistBox\fP"
.br
.ti -1c
.RI "float \fBDistCenter\fP"
.br
.ti -1c
.RI "float \fBDistAxial\fP"
.br
.ti -1c
.RI "\fBImGuiSelectionUserData\fP \fBSelectionUserData\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ImGuiNavItemData::ImGuiNavItemData ()\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void ImGuiNavItemData::Clear ()\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "float ImGuiNavItemData::DistAxial"

.SS "float ImGuiNavItemData::DistBox"

.SS "float ImGuiNavItemData::DistCenter"

.SS "\fBImGuiID\fP ImGuiNavItemData::FocusScopeId"

.SS "\fBImGuiID\fP ImGuiNavItemData::ID"

.SS "\fBImGuiItemFlags\fP ImGuiNavItemData::ItemFlags"

.SS "\fBImRect\fP ImGuiNavItemData::RectRel"

.SS "\fBImGuiSelectionUserData\fP ImGuiNavItemData::SelectionUserData"

.SS "\fBImGuiWindow\fP* ImGuiNavItemData::Window"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
