.TH "ImGuiTableTempData" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiTableTempData
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imgui_internal\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImGuiTableTempData\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBTableIndex\fP"
.br
.ti -1c
.RI "float \fBLastTimeActive\fP"
.br
.ti -1c
.RI "float \fBAngledHeadersExtraWidth\fP"
.br
.ti -1c
.RI "\fBImVector\fP< \fBImGuiTableHeaderData\fP > \fBAngledHeadersRequests\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBUserOuterSize\fP"
.br
.ti -1c
.RI "\fBImDrawListSplitter\fP \fBDrawSplitter\fP"
.br
.ti -1c
.RI "\fBImRect\fP \fBHostBackupWorkRect\fP"
.br
.ti -1c
.RI "\fBImRect\fP \fBHostBackupParentWorkRect\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBHostBackupPrevLineSize\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBHostBackupCurrLineSize\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBHostBackupCursorMaxPos\fP"
.br
.ti -1c
.RI "\fBImVec1\fP \fBHostBackupColumnsOffset\fP"
.br
.ti -1c
.RI "float \fBHostBackupItemWidth\fP"
.br
.ti -1c
.RI "int \fBHostBackupItemWidthStackSize\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ImGuiTableTempData::ImGuiTableTempData ()\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "float ImGuiTableTempData::AngledHeadersExtraWidth"

.SS "\fBImVector\fP<\fBImGuiTableHeaderData\fP> ImGuiTableTempData::AngledHeadersRequests"

.SS "\fBImDrawListSplitter\fP ImGuiTableTempData::DrawSplitter"

.SS "\fBImVec1\fP ImGuiTableTempData::HostBackupColumnsOffset"

.SS "\fBImVec2\fP ImGuiTableTempData::HostBackupCurrLineSize"

.SS "\fBImVec2\fP ImGuiTableTempData::HostBackupCursorMaxPos"

.SS "float ImGuiTableTempData::HostBackupItemWidth"

.SS "int ImGuiTableTempData::HostBackupItemWidthStackSize"

.SS "\fBImRect\fP ImGuiTableTempData::HostBackupParentWorkRect"

.SS "\fBImVec2\fP ImGuiTableTempData::HostBackupPrevLineSize"

.SS "\fBImRect\fP ImGuiTableTempData::HostBackupWorkRect"

.SS "float ImGuiTableTempData::LastTimeActive"

.SS "int ImGuiTableTempData::TableIndex"

.SS "\fBImVec2\fP ImGuiTableTempData::UserOuterSize"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
