.TH "ImGuiStackLevelInfo" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiStackLevelInfo
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imgui_internal\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImGuiStackLevelInfo\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBImGuiID\fP \fBID\fP"
.br
.ti -1c
.RI "\fBImS8\fP \fBQueryFrameCount\fP"
.br
.ti -1c
.RI "bool \fBQuerySuccess\fP"
.br
.ti -1c
.RI "\fBImGuiDataType\fP \fBDataType\fP: 8"
.br
.ti -1c
.RI "char \fBDesc\fP [57]"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ImGuiStackLevelInfo::ImGuiStackLevelInfo ()\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBImGuiDataType\fP ImGuiStackLevelInfo::DataType"

.SS "char ImGuiStackLevelInfo::Desc[57]"

.SS "\fBImGuiID\fP ImGuiStackLevelInfo::ID"

.SS "\fBImS8\fP ImGuiStackLevelInfo::QueryFrameCount"

.SS "bool ImGuiStackLevelInfo::QuerySuccess"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
