.TH "ImGuiKeyRoutingData" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiKeyRoutingData
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imgui_internal\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImGuiKeyRoutingData\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBImGuiKeyRoutingIndex\fP \fBNextEntryIndex\fP"
.br
.ti -1c
.RI "\fBImU16\fP \fBMods\fP"
.br
.ti -1c
.RI "\fBImU8\fP \fBRoutingCurrScore\fP"
.br
.ti -1c
.RI "\fBImU8\fP \fBRoutingNextScore\fP"
.br
.ti -1c
.RI "\fBImGuiID\fP \fBRoutingCurr\fP"
.br
.ti -1c
.RI "\fBImGuiID\fP \fBRoutingNext\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ImGuiKeyRoutingData::ImGuiKeyRoutingData ()\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBImU16\fP ImGuiKeyRoutingData::Mods"

.SS "\fBImGuiKeyRoutingIndex\fP ImGuiKeyRoutingData::NextEntryIndex"

.SS "\fBImGuiID\fP ImGuiKeyRoutingData::RoutingCurr"

.SS "\fBImU8\fP ImGuiKeyRoutingData::RoutingCurrScore"

.SS "\fBImGuiID\fP ImGuiKeyRoutingData::RoutingNext"

.SS "\fBImU8\fP ImGuiKeyRoutingData::RoutingNextScore"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
