.TH "ImGuiTableSortSpecs" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiTableSortSpecs
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imgui\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImGuiTableSortSpecs\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const \fBImGuiTableColumnSortSpecs\fP * \fBSpecs\fP"
.br
.ti -1c
.RI "int \fBSpecsCount\fP"
.br
.ti -1c
.RI "bool \fBSpecsDirty\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ImGuiTableSortSpecs::ImGuiTableSortSpecs ()\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "const \fBImGuiTableColumnSortSpecs\fP* ImGuiTableSortSpecs::Specs"

.SS "int ImGuiTableSortSpecs::SpecsCount"

.SS "bool ImGuiTableSortSpecs::SpecsDirty"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
