.TH "ImGuiTypingSelectRequest" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiTypingSelectRequest
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imgui_internal\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBImGuiTypingSelectFlags\fP \fBFlags\fP"
.br
.ti -1c
.RI "int \fBSearchBufferLen\fP"
.br
.ti -1c
.RI "const char * \fBSearchBuffer\fP"
.br
.ti -1c
.RI "bool \fBSelectRequest\fP"
.br
.ti -1c
.RI "bool \fBSingleCharMode\fP"
.br
.ti -1c
.RI "\fBImS8\fP \fBSingleCharSize\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBImGuiTypingSelectFlags\fP ImGuiTypingSelectRequest::Flags"

.SS "const char* ImGuiTypingSelectRequest::SearchBuffer"

.SS "int ImGuiTypingSelectRequest::SearchBufferLen"

.SS "bool ImGuiTypingSelectRequest::SelectRequest"

.SS "bool ImGuiTypingSelectRequest::SingleCharMode"

.SS "\fBImS8\fP ImGuiTypingSelectRequest::SingleCharSize"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
