.TH "ImGuiTableHeaderData" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiTableHeaderData
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imgui_internal\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBImGuiTableColumnIdx\fP \fBIndex\fP"
.br
.ti -1c
.RI "\fBImU32\fP \fBTextColor\fP"
.br
.ti -1c
.RI "\fBImU32\fP \fBBgColor0\fP"
.br
.ti -1c
.RI "\fBImU32\fP \fBBgColor1\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBImU32\fP ImGuiTableHeaderData::BgColor0"

.SS "\fBImU32\fP ImGuiTableHeaderData::BgColor1"

.SS "\fBImGuiTableColumnIdx\fP ImGuiTableHeaderData::Index"

.SS "\fBImU32\fP ImGuiTableHeaderData::TextColor"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
