.TH "ImGuiPtrOrIndex" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiPtrOrIndex
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imgui_internal\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImGuiPtrOrIndex\fP (void *ptr)"
.br
.ti -1c
.RI "\fBImGuiPtrOrIndex\fP (int index)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void * \fBPtr\fP"
.br
.ti -1c
.RI "int \fBIndex\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ImGuiPtrOrIndex::ImGuiPtrOrIndex (void * ptr)\fR [inline]\fP"

.SS "ImGuiPtrOrIndex::ImGuiPtrOrIndex (int index)\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "int ImGuiPtrOrIndex::Index"

.SS "void* ImGuiPtrOrIndex::Ptr"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
