.TH "ImGuiWindowStackData" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiWindowStackData
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imgui_internal\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBImGuiWindow\fP * \fBWindow\fP"
.br
.ti -1c
.RI "\fBImGuiLastItemData\fP \fBParentLastItemDataBackup\fP"
.br
.ti -1c
.RI "\fBImGuiErrorRecoveryState\fP \fBStackSizesInBegin\fP"
.br
.ti -1c
.RI "bool \fBDisabledOverrideReenable\fP"
.br
.ti -1c
.RI "float \fBDisabledOverrideReenableAlphaBackup\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "bool ImGuiWindowStackData::DisabledOverrideReenable"

.SS "float ImGuiWindowStackData::DisabledOverrideReenableAlphaBackup"

.SS "\fBImGuiLastItemData\fP ImGuiWindowStackData::ParentLastItemDataBackup"

.SS "\fBImGuiErrorRecoveryState\fP ImGuiWindowStackData::StackSizesInBegin"

.SS "\fBImGuiWindow\fP* ImGuiWindowStackData::Window"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
