.TH "ImGuiPlatformImeData" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiPlatformImeData
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imgui\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImGuiPlatformImeData\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBWantVisible\fP"
.br
.ti -1c
.RI "bool \fBWantTextInput\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBInputPos\fP"
.br
.ti -1c
.RI "float \fBInputLineHeight\fP"
.br
.ti -1c
.RI "\fBImGuiID\fP \fBViewportId\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ImGuiPlatformImeData::ImGuiPlatformImeData ()\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "float ImGuiPlatformImeData::InputLineHeight"

.SS "\fBImVec2\fP ImGuiPlatformImeData::InputPos"

.SS "\fBImGuiID\fP ImGuiPlatformImeData::ViewportId"

.SS "bool ImGuiPlatformImeData::WantTextInput"

.SS "bool ImGuiPlatformImeData::WantVisible"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
