.TH "ImGuiInputEventMouseButton" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiInputEventMouseButton
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imgui_internal\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBButton\fP"
.br
.ti -1c
.RI "bool \fBDown\fP"
.br
.ti -1c
.RI "\fBImGuiMouseSource\fP \fBMouseSource\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int ImGuiInputEventMouseButton::Button"

.SS "bool ImGuiInputEventMouseButton::Down"

.SS "\fBImGuiMouseSource\fP ImGuiInputEventMouseButton::MouseSource"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
