.TH "ImGuiStyleVarInfo" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiStyleVarInfo
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imgui_internal\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void * \fBGetVarPtr\fP (void *parent) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBImU32\fP \fBCount\fP: 8"
.br
.ti -1c
.RI "\fBImGuiDataType\fP \fBDataType\fP: 8"
.br
.ti -1c
.RI "\fBImU32\fP \fBOffset\fP: 16"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void * ImGuiStyleVarInfo::GetVarPtr (void * parent) const\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBImU32\fP ImGuiStyleVarInfo::Count"

.SS "\fBImGuiDataType\fP ImGuiStyleVarInfo::DataType"

.SS "\fBImU32\fP ImGuiStyleVarInfo::Offset"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
