.TH "ImGui_ImplOpenGL3_Data" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGui_ImplOpenGL3_Data
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImGui_ImplOpenGL3_Data\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GLuint \fBGlVersion\fP"
.br
.ti -1c
.RI "char \fBGlslVersionString\fP [32]"
.br
.ti -1c
.RI "bool \fBGlProfileIsES2\fP"
.br
.ti -1c
.RI "bool \fBGlProfileIsES3\fP"
.br
.ti -1c
.RI "bool \fBGlProfileIsCompat\fP"
.br
.ti -1c
.RI "GLint \fBGlProfileMask\fP"
.br
.ti -1c
.RI "GLuint \fBFontTexture\fP"
.br
.ti -1c
.RI "GLuint \fBShaderHandle\fP"
.br
.ti -1c
.RI "GLint \fBAttribLocationTex\fP"
.br
.ti -1c
.RI "GLint \fBAttribLocationProjMtx\fP"
.br
.ti -1c
.RI "GLuint \fBAttribLocationVtxPos\fP"
.br
.ti -1c
.RI "GLuint \fBAttribLocationVtxUV\fP"
.br
.ti -1c
.RI "GLuint \fBAttribLocationVtxColor\fP"
.br
.ti -1c
.RI "unsigned int \fBVboHandle\fP"
.br
.ti -1c
.RI "unsigned int \fBElementsHandle\fP"
.br
.ti -1c
.RI "GLsizeiptr \fBVertexBufferSize\fP"
.br
.ti -1c
.RI "GLsizeiptr \fBIndexBufferSize\fP"
.br
.ti -1c
.RI "bool \fBHasPolygonMode\fP"
.br
.ti -1c
.RI "bool \fBHasClipOrigin\fP"
.br
.ti -1c
.RI "bool \fBUseBufferSubData\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ImGui_ImplOpenGL3_Data::ImGui_ImplOpenGL3_Data ()\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "GLint ImGui_ImplOpenGL3_Data::AttribLocationProjMtx"

.SS "GLint ImGui_ImplOpenGL3_Data::AttribLocationTex"

.SS "GLuint ImGui_ImplOpenGL3_Data::AttribLocationVtxColor"

.SS "GLuint ImGui_ImplOpenGL3_Data::AttribLocationVtxPos"

.SS "GLuint ImGui_ImplOpenGL3_Data::AttribLocationVtxUV"

.SS "unsigned int ImGui_ImplOpenGL3_Data::ElementsHandle"

.SS "GLuint ImGui_ImplOpenGL3_Data::FontTexture"

.SS "bool ImGui_ImplOpenGL3_Data::GlProfileIsCompat"

.SS "bool ImGui_ImplOpenGL3_Data::GlProfileIsES2"

.SS "bool ImGui_ImplOpenGL3_Data::GlProfileIsES3"

.SS "GLint ImGui_ImplOpenGL3_Data::GlProfileMask"

.SS "char ImGui_ImplOpenGL3_Data::GlslVersionString[32]"

.SS "GLuint ImGui_ImplOpenGL3_Data::GlVersion"

.SS "bool ImGui_ImplOpenGL3_Data::HasClipOrigin"

.SS "bool ImGui_ImplOpenGL3_Data::HasPolygonMode"

.SS "GLsizeiptr ImGui_ImplOpenGL3_Data::IndexBufferSize"

.SS "GLuint ImGui_ImplOpenGL3_Data::ShaderHandle"

.SS "bool ImGui_ImplOpenGL3_Data::UseBufferSubData"

.SS "unsigned int ImGui_ImplOpenGL3_Data::VboHandle"

.SS "GLsizeiptr ImGui_ImplOpenGL3_Data::VertexBufferSize"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
