.TH "ImGuiMetricsConfig" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiMetricsConfig
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imgui_internal\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBShowDebugLog\fP = false"
.br
.ti -1c
.RI "bool \fBShowIDStackTool\fP = false"
.br
.ti -1c
.RI "bool \fBShowWindowsRects\fP = false"
.br
.ti -1c
.RI "bool \fBShowWindowsBeginOrder\fP = false"
.br
.ti -1c
.RI "bool \fBShowTablesRects\fP = false"
.br
.ti -1c
.RI "bool \fBShowDrawCmdMesh\fP = true"
.br
.ti -1c
.RI "bool \fBShowDrawCmdBoundingBoxes\fP = true"
.br
.ti -1c
.RI "bool \fBShowTextEncodingViewer\fP = false"
.br
.ti -1c
.RI "int \fBShowWindowsRectsType\fP = \-1"
.br
.ti -1c
.RI "int \fBShowTablesRectsType\fP = \-1"
.br
.ti -1c
.RI "int \fBHighlightMonitorIdx\fP = \-1"
.br
.ti -1c
.RI "\fBImGuiID\fP \fBHighlightViewportID\fP = 0"
.br
.ti -1c
.RI "bool \fBShowFontPreview\fP = true"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int ImGuiMetricsConfig::HighlightMonitorIdx = \-1"

.SS "\fBImGuiID\fP ImGuiMetricsConfig::HighlightViewportID = 0"

.SS "bool ImGuiMetricsConfig::ShowDebugLog = false"

.SS "bool ImGuiMetricsConfig::ShowDrawCmdBoundingBoxes = true"

.SS "bool ImGuiMetricsConfig::ShowDrawCmdMesh = true"

.SS "bool ImGuiMetricsConfig::ShowFontPreview = true"

.SS "bool ImGuiMetricsConfig::ShowIDStackTool = false"

.SS "bool ImGuiMetricsConfig::ShowTablesRects = false"

.SS "int ImGuiMetricsConfig::ShowTablesRectsType = \-1"

.SS "bool ImGuiMetricsConfig::ShowTextEncodingViewer = false"

.SS "bool ImGuiMetricsConfig::ShowWindowsBeginOrder = false"

.SS "bool ImGuiMetricsConfig::ShowWindowsRects = false"

.SS "int ImGuiMetricsConfig::ShowWindowsRectsType = \-1"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
