.TH "ImGuiBoxSelectState" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiBoxSelectState
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imgui_internal\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImGuiBoxSelectState\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBImGuiID\fP \fBID\fP"
.br
.ti -1c
.RI "bool \fBIsActive\fP"
.br
.ti -1c
.RI "bool \fBIsStarting\fP"
.br
.ti -1c
.RI "bool \fBIsStartedFromVoid\fP"
.br
.ti -1c
.RI "bool \fBIsStartedSetNavIdOnce\fP"
.br
.ti -1c
.RI "bool \fBRequestClear\fP"
.br
.ti -1c
.RI "\fBImGuiKeyChord\fP \fBKeyMods\fP: 16"
.br
.ti -1c
.RI "\fBImVec2\fP \fBStartPosRel\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBEndPosRel\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBScrollAccum\fP"
.br
.ti -1c
.RI "\fBImGuiWindow\fP * \fBWindow\fP"
.br
.ti -1c
.RI "bool \fBUnclipMode\fP"
.br
.ti -1c
.RI "\fBImRect\fP \fBUnclipRect\fP"
.br
.ti -1c
.RI "\fBImRect\fP \fBBoxSelectRectPrev\fP"
.br
.ti -1c
.RI "\fBImRect\fP \fBBoxSelectRectCurr\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ImGuiBoxSelectState::ImGuiBoxSelectState ()\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBImRect\fP ImGuiBoxSelectState::BoxSelectRectCurr"

.SS "\fBImRect\fP ImGuiBoxSelectState::BoxSelectRectPrev"

.SS "\fBImVec2\fP ImGuiBoxSelectState::EndPosRel"

.SS "\fBImGuiID\fP ImGuiBoxSelectState::ID"

.SS "bool ImGuiBoxSelectState::IsActive"

.SS "bool ImGuiBoxSelectState::IsStartedFromVoid"

.SS "bool ImGuiBoxSelectState::IsStartedSetNavIdOnce"

.SS "bool ImGuiBoxSelectState::IsStarting"

.SS "\fBImGuiKeyChord\fP ImGuiBoxSelectState::KeyMods"

.SS "bool ImGuiBoxSelectState::RequestClear"

.SS "\fBImVec2\fP ImGuiBoxSelectState::ScrollAccum"

.SS "\fBImVec2\fP ImGuiBoxSelectState::StartPosRel"

.SS "bool ImGuiBoxSelectState::UnclipMode"

.SS "\fBImRect\fP ImGuiBoxSelectState::UnclipRect"

.SS "\fBImGuiWindow\fP* ImGuiBoxSelectState::Window"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
