.TH "ImGuiTreeNodeStackData" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiTreeNodeStackData
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imgui_internal\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBImGuiID\fP \fBID\fP"
.br
.ti -1c
.RI "\fBImGuiTreeNodeFlags\fP \fBTreeFlags\fP"
.br
.ti -1c
.RI "\fBImGuiItemFlags\fP \fBItemFlags\fP"
.br
.ti -1c
.RI "\fBImRect\fP \fBNavRect\fP"
.br
.ti -1c
.RI "float \fBDrawLinesX1\fP"
.br
.ti -1c
.RI "float \fBDrawLinesToNodesY2\fP"
.br
.ti -1c
.RI "\fBImGuiTableColumnIdx\fP \fBDrawLinesTableColumn\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBImGuiTableColumnIdx\fP ImGuiTreeNodeStackData::DrawLinesTableColumn"

.SS "float ImGuiTreeNodeStackData::DrawLinesToNodesY2"

.SS "float ImGuiTreeNodeStackData::DrawLinesX1"

.SS "\fBImGuiID\fP ImGuiTreeNodeStackData::ID"

.SS "\fBImGuiItemFlags\fP ImGuiTreeNodeStackData::ItemFlags"

.SS "\fBImRect\fP ImGuiTreeNodeStackData::NavRect"

.SS "\fBImGuiTreeNodeFlags\fP ImGuiTreeNodeStackData::TreeFlags"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
