.TH "ImGuiInputTextDeactivatedState" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiInputTextDeactivatedState
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imgui_internal\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImGuiInputTextDeactivatedState\fP ()"
.br
.ti -1c
.RI "void \fBClearFreeMemory\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBImGuiID\fP \fBID\fP"
.br
.ti -1c
.RI "\fBImVector\fP< char > \fBTextA\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ImGuiInputTextDeactivatedState::ImGuiInputTextDeactivatedState ()\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void ImGuiInputTextDeactivatedState::ClearFreeMemory ()\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBImGuiID\fP ImGuiInputTextDeactivatedState::ID"

.SS "\fBImVector\fP<char> ImGuiInputTextDeactivatedState::TextA"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
