.TH "ImGuiGetNameFromIndexOldToNewCallbackData" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiGetNameFromIndexOldToNewCallbackData
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void * \fBUserData\fP"
.br
.ti -1c
.RI "bool(* \fBOldCallback\fP )(void *, int, const char **)"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "bool(* ImGuiGetNameFromIndexOldToNewCallbackData::OldCallback) (void *, int, const char **)"

.SS "void* ImGuiGetNameFromIndexOldToNewCallbackData::UserData"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
