.TH "ImGuiMultiSelectTempData" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiMultiSelectTempData
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imgui_internal\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImGuiMultiSelectTempData\fP ()"
.br
.ti -1c
.RI "void \fBClear\fP ()"
.br
.ti -1c
.RI "void \fBClearIO\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBImGuiMultiSelectIO\fP \fBIO\fP"
.br
.ti -1c
.RI "\fBImGuiMultiSelectState\fP * \fBStorage\fP"
.br
.ti -1c
.RI "\fBImGuiID\fP \fBFocusScopeId\fP"
.br
.ti -1c
.RI "\fBImGuiMultiSelectFlags\fP \fBFlags\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBScopeRectMin\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBBackupCursorMaxPos\fP"
.br
.ti -1c
.RI "\fBImGuiSelectionUserData\fP \fBLastSubmittedItem\fP"
.br
.ti -1c
.RI "\fBImGuiID\fP \fBBoxSelectId\fP"
.br
.ti -1c
.RI "\fBImGuiKeyChord\fP \fBKeyMods\fP"
.br
.ti -1c
.RI "\fBImS8\fP \fBLoopRequestSetAll\fP"
.br
.ti -1c
.RI "bool \fBIsEndIO\fP"
.br
.ti -1c
.RI "bool \fBIsFocused\fP"
.br
.ti -1c
.RI "bool \fBIsKeyboardSetRange\fP"
.br
.ti -1c
.RI "bool \fBNavIdPassedBy\fP"
.br
.ti -1c
.RI "bool \fBRangeSrcPassedBy\fP"
.br
.ti -1c
.RI "bool \fBRangeDstPassedBy\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ImGuiMultiSelectTempData::ImGuiMultiSelectTempData ()\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void ImGuiMultiSelectTempData::Clear ()\fR [inline]\fP"

.SS "void ImGuiMultiSelectTempData::ClearIO ()\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBImVec2\fP ImGuiMultiSelectTempData::BackupCursorMaxPos"

.SS "\fBImGuiID\fP ImGuiMultiSelectTempData::BoxSelectId"

.SS "\fBImGuiMultiSelectFlags\fP ImGuiMultiSelectTempData::Flags"

.SS "\fBImGuiID\fP ImGuiMultiSelectTempData::FocusScopeId"

.SS "\fBImGuiMultiSelectIO\fP ImGuiMultiSelectTempData::IO"

.SS "bool ImGuiMultiSelectTempData::IsEndIO"

.SS "bool ImGuiMultiSelectTempData::IsFocused"

.SS "bool ImGuiMultiSelectTempData::IsKeyboardSetRange"

.SS "\fBImGuiKeyChord\fP ImGuiMultiSelectTempData::KeyMods"

.SS "\fBImGuiSelectionUserData\fP ImGuiMultiSelectTempData::LastSubmittedItem"

.SS "\fBImS8\fP ImGuiMultiSelectTempData::LoopRequestSetAll"

.SS "bool ImGuiMultiSelectTempData::NavIdPassedBy"

.SS "bool ImGuiMultiSelectTempData::RangeDstPassedBy"

.SS "bool ImGuiMultiSelectTempData::RangeSrcPassedBy"

.SS "\fBImVec2\fP ImGuiMultiSelectTempData::ScopeRectMin"

.SS "\fBImGuiMultiSelectState\fP* ImGuiMultiSelectTempData::Storage"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
