.TH "ImGuiSizeCallbackData" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiSizeCallbackData
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imgui\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void * \fBUserData\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBPos\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBCurrentSize\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBDesiredSize\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBImVec2\fP ImGuiSizeCallbackData::CurrentSize"

.SS "\fBImVec2\fP ImGuiSizeCallbackData::DesiredSize"

.SS "\fBImVec2\fP ImGuiSizeCallbackData::Pos"

.SS "void* ImGuiSizeCallbackData::UserData"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
