.TH "ImGuiSelectionExternalStorage" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiSelectionExternalStorage
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imgui\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIMGUI_API\fP \fBImGuiSelectionExternalStorage\fP ()"
.br
.ti -1c
.RI "\fBIMGUI_API\fP void \fBApplyRequests\fP (\fBImGuiMultiSelectIO\fP *ms_io)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void * \fBUserData\fP"
.br
.ti -1c
.RI "void(* \fBAdapterSetItemSelected\fP )(\fBImGuiSelectionExternalStorage\fP *self, int idx, bool selected)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ImGuiSelectionExternalStorage::ImGuiSelectionExternalStorage ()"

.SH "Member Function Documentation"
.PP 
.SS "void ImGuiSelectionExternalStorage::ApplyRequests (\fBImGuiMultiSelectIO\fP * ms_io)"

.SH "Member Data Documentation"
.PP 
.SS "void(* ImGuiSelectionExternalStorage::AdapterSetItemSelected) (\fBImGuiSelectionExternalStorage\fP *self, int idx, bool selected)"

.SS "void* ImGuiSelectionExternalStorage::UserData"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
