.TH "ImGuiTextFilter::ImGuiTextRange" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiTextFilter::ImGuiTextRange
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imgui\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImGuiTextRange\fP ()"
.br
.ti -1c
.RI "\fBImGuiTextRange\fP (const char *_b, const char *_e)"
.br
.ti -1c
.RI "bool \fBempty\fP () const"
.br
.ti -1c
.RI "\fBIMGUI_API\fP void \fBsplit\fP (char separator, \fBImVector\fP< \fBImGuiTextRange\fP > *out) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBb\fP"
.br
.ti -1c
.RI "const char * \fBe\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ImGuiTextFilter::ImGuiTextRange::ImGuiTextRange ()\fR [inline]\fP"

.SS "ImGuiTextFilter::ImGuiTextRange::ImGuiTextRange (const char * _b, const char * _e)\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool ImGuiTextFilter::ImGuiTextRange::empty () const\fR [inline]\fP"

.SS "void ImGuiTextFilter::ImGuiTextRange::split (char separator, \fBImVector\fP< \fBImGuiTextRange\fP > * out) const"

.SH "Member Data Documentation"
.PP 
.SS "const char* ImGuiTextFilter::ImGuiTextRange::b"

.SS "const char* ImGuiTextFilter::ImGuiTextRange::e"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
