.TH "ImGuiDataTypeInfo" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiDataTypeInfo
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imgui_internal\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "size_t \fBSize\fP"
.br
.ti -1c
.RI "const char * \fBName\fP"
.br
.ti -1c
.RI "const char * \fBPrintFmt\fP"
.br
.ti -1c
.RI "const char * \fBScanFmt\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "const char* ImGuiDataTypeInfo::Name"

.SS "const char* ImGuiDataTypeInfo::PrintFmt"

.SS "const char* ImGuiDataTypeInfo::ScanFmt"

.SS "size_t ImGuiDataTypeInfo::Size"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
