.TH "ImGuiTableSettings" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiTableSettings
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imgui_internal\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImGuiTableSettings\fP ()"
.br
.ti -1c
.RI "\fBImGuiTableColumnSettings\fP * \fBGetColumnSettings\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBImGuiID\fP \fBID\fP"
.br
.ti -1c
.RI "\fBImGuiTableFlags\fP \fBSaveFlags\fP"
.br
.ti -1c
.RI "float \fBRefScale\fP"
.br
.ti -1c
.RI "\fBImGuiTableColumnIdx\fP \fBColumnsCount\fP"
.br
.ti -1c
.RI "\fBImGuiTableColumnIdx\fP \fBColumnsCountMax\fP"
.br
.ti -1c
.RI "bool \fBWantApply\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ImGuiTableSettings::ImGuiTableSettings ()\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBImGuiTableColumnSettings\fP * ImGuiTableSettings::GetColumnSettings ()\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBImGuiTableColumnIdx\fP ImGuiTableSettings::ColumnsCount"

.SS "\fBImGuiTableColumnIdx\fP ImGuiTableSettings::ColumnsCountMax"

.SS "\fBImGuiID\fP ImGuiTableSettings::ID"

.SS "float ImGuiTableSettings::RefScale"

.SS "\fBImGuiTableFlags\fP ImGuiTableSettings::SaveFlags"

.SS "bool ImGuiTableSettings::WantApply"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
