.TH "ImGuiViewport" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiViewport
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imgui\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImGuiViewport\fP ()"
.br
.ti -1c
.RI "\fBImVec2\fP \fBGetCenter\fP () const"
.br
.ti -1c
.RI "\fBImVec2\fP \fBGetWorkCenter\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBImGuiID\fP \fBID\fP"
.br
.ti -1c
.RI "\fBImGuiViewportFlags\fP \fBFlags\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBPos\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBSize\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBWorkPos\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBWorkSize\fP"
.br
.ti -1c
.RI "void * \fBPlatformHandle\fP"
.br
.ti -1c
.RI "void * \fBPlatformHandleRaw\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ImGuiViewport::ImGuiViewport ()\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBImVec2\fP ImGuiViewport::GetCenter () const\fR [inline]\fP"

.SS "\fBImVec2\fP ImGuiViewport::GetWorkCenter () const\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBImGuiViewportFlags\fP ImGuiViewport::Flags"

.SS "\fBImGuiID\fP ImGuiViewport::ID"

.SS "void* ImGuiViewport::PlatformHandle"

.SS "void* ImGuiViewport::PlatformHandleRaw"

.SS "\fBImVec2\fP ImGuiViewport::Pos"

.SS "\fBImVec2\fP ImGuiViewport::Size"

.SS "\fBImVec2\fP ImGuiViewport::WorkPos"

.SS "\fBImVec2\fP ImGuiViewport::WorkSize"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
