.TH "ImGuiLocEntry" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiLocEntry
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imgui_internal\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBImGuiLocKey\fP \fBKey\fP"
.br
.ti -1c
.RI "const char * \fBText\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBImGuiLocKey\fP ImGuiLocEntry::Key"

.SS "const char* ImGuiLocEntry::Text"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
