.TH "ImGuiTableColumnSettings" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiTableColumnSettings
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imgui_internal\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImGuiTableColumnSettings\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBWidthOrWeight\fP"
.br
.ti -1c
.RI "\fBImGuiID\fP \fBUserID\fP"
.br
.ti -1c
.RI "\fBImGuiTableColumnIdx\fP \fBIndex\fP"
.br
.ti -1c
.RI "\fBImGuiTableColumnIdx\fP \fBDisplayOrder\fP"
.br
.ti -1c
.RI "\fBImGuiTableColumnIdx\fP \fBSortOrder\fP"
.br
.ti -1c
.RI "\fBImU8\fP \fBSortDirection\fP: 2"
.br
.ti -1c
.RI "\fBImS8\fP \fBIsEnabled\fP: 2"
.br
.ti -1c
.RI "\fBImU8\fP \fBIsStretch\fP: 1"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ImGuiTableColumnSettings::ImGuiTableColumnSettings ()\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBImGuiTableColumnIdx\fP ImGuiTableColumnSettings::DisplayOrder"

.SS "\fBImGuiTableColumnIdx\fP ImGuiTableColumnSettings::Index"

.SS "\fBImS8\fP ImGuiTableColumnSettings::IsEnabled"

.SS "\fBImU8\fP ImGuiTableColumnSettings::IsStretch"

.SS "\fBImU8\fP ImGuiTableColumnSettings::SortDirection"

.SS "\fBImGuiTableColumnIdx\fP ImGuiTableColumnSettings::SortOrder"

.SS "\fBImGuiID\fP ImGuiTableColumnSettings::UserID"

.SS "float ImGuiTableColumnSettings::WidthOrWeight"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
