.TH "ImGui_ImplGlfw_Data" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGui_ImplGlfw_Data
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImGui_ImplGlfw_Data\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBGLFWwindow\fP * \fBWindow\fP"
.br
.ti -1c
.RI "\fBGlfwClientApi\fP \fBClientApi\fP"
.br
.ti -1c
.RI "double \fBTime\fP"
.br
.ti -1c
.RI "\fBGLFWwindow\fP * \fBMouseWindow\fP"
.br
.ti -1c
.RI "\fBGLFWcursor\fP * \fBMouseCursors\fP [\fBImGuiMouseCursor_COUNT\fP]"
.br
.ti -1c
.RI "\fBImVec2\fP \fBLastValidMousePos\fP"
.br
.ti -1c
.RI "bool \fBInstalledCallbacks\fP"
.br
.ti -1c
.RI "bool \fBCallbacksChainForAllWindows\fP"
.br
.ti -1c
.RI "char \fBBackendPlatformName\fP [32]"
.br
.ti -1c
.RI "\fBGLFWwindowfocusfun\fP \fBPrevUserCallbackWindowFocus\fP"
.br
.ti -1c
.RI "\fBGLFWcursorposfun\fP \fBPrevUserCallbackCursorPos\fP"
.br
.ti -1c
.RI "\fBGLFWcursorenterfun\fP \fBPrevUserCallbackCursorEnter\fP"
.br
.ti -1c
.RI "\fBGLFWmousebuttonfun\fP \fBPrevUserCallbackMousebutton\fP"
.br
.ti -1c
.RI "\fBGLFWscrollfun\fP \fBPrevUserCallbackScroll\fP"
.br
.ti -1c
.RI "\fBGLFWkeyfun\fP \fBPrevUserCallbackKey\fP"
.br
.ti -1c
.RI "\fBGLFWcharfun\fP \fBPrevUserCallbackChar\fP"
.br
.ti -1c
.RI "\fBGLFWmonitorfun\fP \fBPrevUserCallbackMonitor\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ImGui_ImplGlfw_Data::ImGui_ImplGlfw_Data ()\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "char ImGui_ImplGlfw_Data::BackendPlatformName[32]"

.SS "bool ImGui_ImplGlfw_Data::CallbacksChainForAllWindows"

.SS "\fBGlfwClientApi\fP ImGui_ImplGlfw_Data::ClientApi"

.SS "bool ImGui_ImplGlfw_Data::InstalledCallbacks"

.SS "\fBImVec2\fP ImGui_ImplGlfw_Data::LastValidMousePos"

.SS "\fBGLFWcursor\fP* ImGui_ImplGlfw_Data::MouseCursors[\fBImGuiMouseCursor_COUNT\fP]"

.SS "\fBGLFWwindow\fP* ImGui_ImplGlfw_Data::MouseWindow"

.SS "\fBGLFWcharfun\fP ImGui_ImplGlfw_Data::PrevUserCallbackChar"

.SS "\fBGLFWcursorenterfun\fP ImGui_ImplGlfw_Data::PrevUserCallbackCursorEnter"

.SS "\fBGLFWcursorposfun\fP ImGui_ImplGlfw_Data::PrevUserCallbackCursorPos"

.SS "\fBGLFWkeyfun\fP ImGui_ImplGlfw_Data::PrevUserCallbackKey"

.SS "\fBGLFWmonitorfun\fP ImGui_ImplGlfw_Data::PrevUserCallbackMonitor"

.SS "\fBGLFWmousebuttonfun\fP ImGui_ImplGlfw_Data::PrevUserCallbackMousebutton"

.SS "\fBGLFWscrollfun\fP ImGui_ImplGlfw_Data::PrevUserCallbackScroll"

.SS "\fBGLFWwindowfocusfun\fP ImGui_ImplGlfw_Data::PrevUserCallbackWindowFocus"

.SS "double ImGui_ImplGlfw_Data::Time"

.SS "\fBGLFWwindow\fP* ImGui_ImplGlfw_Data::Window"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
