.TH "ImGuiTabBarSection" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiTabBarSection
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImGuiTabBarSection\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBTabCount\fP"
.br
.ti -1c
.RI "float \fBWidth\fP"
.br
.ti -1c
.RI "float \fBSpacing\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ImGuiTabBarSection::ImGuiTabBarSection ()\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "float ImGuiTabBarSection::Spacing"

.SS "int ImGuiTabBarSection::TabCount"

.SS "float ImGuiTabBarSection::Width"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
