.TH "ImGuiPopupData" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiPopupData
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imgui_internal\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImGuiPopupData\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBImGuiID\fP \fBPopupId\fP"
.br
.ti -1c
.RI "\fBImGuiWindow\fP * \fBWindow\fP"
.br
.ti -1c
.RI "\fBImGuiWindow\fP * \fBRestoreNavWindow\fP"
.br
.ti -1c
.RI "int \fBParentNavLayer\fP"
.br
.ti -1c
.RI "int \fBOpenFrameCount\fP"
.br
.ti -1c
.RI "\fBImGuiID\fP \fBOpenParentId\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBOpenPopupPos\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBOpenMousePos\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ImGuiPopupData::ImGuiPopupData ()\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "int ImGuiPopupData::OpenFrameCount"

.SS "\fBImVec2\fP ImGuiPopupData::OpenMousePos"

.SS "\fBImGuiID\fP ImGuiPopupData::OpenParentId"

.SS "\fBImVec2\fP ImGuiPopupData::OpenPopupPos"

.SS "int ImGuiPopupData::ParentNavLayer"

.SS "\fBImGuiID\fP ImGuiPopupData::PopupId"

.SS "\fBImGuiWindow\fP* ImGuiPopupData::RestoreNavWindow"

.SS "\fBImGuiWindow\fP* ImGuiPopupData::Window"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
