.TH "ImGuiShrinkWidthItem" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiShrinkWidthItem
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imgui_internal\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBIndex\fP"
.br
.ti -1c
.RI "float \fBWidth\fP"
.br
.ti -1c
.RI "float \fBInitialWidth\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int ImGuiShrinkWidthItem::Index"

.SS "float ImGuiShrinkWidthItem::InitialWidth"

.SS "float ImGuiShrinkWidthItem::Width"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
