.TH "ImGuiPlotArrayGetterData" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiPlotArrayGetterData
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImGuiPlotArrayGetterData\fP (const float *values, int stride)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const float * \fBValues\fP"
.br
.ti -1c
.RI "int \fBStride\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ImGuiPlotArrayGetterData::ImGuiPlotArrayGetterData (const float * values, int stride)\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "int ImGuiPlotArrayGetterData::Stride"

.SS "const float* ImGuiPlotArrayGetterData::Values"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
