.TH "ImGuiDemoWindowData" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiDemoWindowData
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB~ImGuiDemoWindowData\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBShowMainMenuBar\fP = false"
.br
.ti -1c
.RI "bool \fBShowAppAssetsBrowser\fP = false"
.br
.ti -1c
.RI "bool \fBShowAppConsole\fP = false"
.br
.ti -1c
.RI "bool \fBShowAppCustomRendering\fP = false"
.br
.ti -1c
.RI "bool \fBShowAppDocuments\fP = false"
.br
.ti -1c
.RI "bool \fBShowAppLog\fP = false"
.br
.ti -1c
.RI "bool \fBShowAppLayout\fP = false"
.br
.ti -1c
.RI "bool \fBShowAppPropertyEditor\fP = false"
.br
.ti -1c
.RI "bool \fBShowAppSimpleOverlay\fP = false"
.br
.ti -1c
.RI "bool \fBShowAppAutoResize\fP = false"
.br
.ti -1c
.RI "bool \fBShowAppConstrainedResize\fP = false"
.br
.ti -1c
.RI "bool \fBShowAppFullscreen\fP = false"
.br
.ti -1c
.RI "bool \fBShowAppLongText\fP = false"
.br
.ti -1c
.RI "bool \fBShowAppWindowTitles\fP = false"
.br
.ti -1c
.RI "bool \fBShowMetrics\fP = false"
.br
.ti -1c
.RI "bool \fBShowDebugLog\fP = false"
.br
.ti -1c
.RI "bool \fBShowIDStackTool\fP = false"
.br
.ti -1c
.RI "bool \fBShowStyleEditor\fP = false"
.br
.ti -1c
.RI "bool \fBShowAbout\fP = false"
.br
.ti -1c
.RI "bool \fBDisableSections\fP = false"
.br
.ti -1c
.RI "\fBExampleTreeNode\fP * \fBDemoTree\fP = NULL"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ImGuiDemoWindowData::~ImGuiDemoWindowData ()\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBExampleTreeNode\fP* ImGuiDemoWindowData::DemoTree = NULL"

.SS "bool ImGuiDemoWindowData::DisableSections = false"

.SS "bool ImGuiDemoWindowData::ShowAbout = false"

.SS "bool ImGuiDemoWindowData::ShowAppAssetsBrowser = false"

.SS "bool ImGuiDemoWindowData::ShowAppAutoResize = false"

.SS "bool ImGuiDemoWindowData::ShowAppConsole = false"

.SS "bool ImGuiDemoWindowData::ShowAppConstrainedResize = false"

.SS "bool ImGuiDemoWindowData::ShowAppCustomRendering = false"

.SS "bool ImGuiDemoWindowData::ShowAppDocuments = false"

.SS "bool ImGuiDemoWindowData::ShowAppFullscreen = false"

.SS "bool ImGuiDemoWindowData::ShowAppLayout = false"

.SS "bool ImGuiDemoWindowData::ShowAppLog = false"

.SS "bool ImGuiDemoWindowData::ShowAppLongText = false"

.SS "bool ImGuiDemoWindowData::ShowAppPropertyEditor = false"

.SS "bool ImGuiDemoWindowData::ShowAppSimpleOverlay = false"

.SS "bool ImGuiDemoWindowData::ShowAppWindowTitles = false"

.SS "bool ImGuiDemoWindowData::ShowDebugLog = false"

.SS "bool ImGuiDemoWindowData::ShowIDStackTool = false"

.SS "bool ImGuiDemoWindowData::ShowMainMenuBar = false"

.SS "bool ImGuiDemoWindowData::ShowMetrics = false"

.SS "bool ImGuiDemoWindowData::ShowStyleEditor = false"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
