.TH "ImGuiOldColumnData" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiOldColumnData
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imgui_internal\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImGuiOldColumnData\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBOffsetNorm\fP"
.br
.ti -1c
.RI "float \fBOffsetNormBeforeResize\fP"
.br
.ti -1c
.RI "\fBImGuiOldColumnFlags\fP \fBFlags\fP"
.br
.ti -1c
.RI "\fBImRect\fP \fBClipRect\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ImGuiOldColumnData::ImGuiOldColumnData ()\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBImRect\fP ImGuiOldColumnData::ClipRect"

.SS "\fBImGuiOldColumnFlags\fP ImGuiOldColumnData::Flags"

.SS "float ImGuiOldColumnData::OffsetNorm"

.SS "float ImGuiOldColumnData::OffsetNormBeforeResize"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
