.TH "ImGuiResizeBorderDef" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiResizeBorderDef
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBImVec2\fP \fBInnerDir\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBSegmentN1\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBSegmentN2\fP"
.br
.ti -1c
.RI "float \fBOuterAngle\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBImVec2\fP ImGuiResizeBorderDef::InnerDir"

.SS "float ImGuiResizeBorderDef::OuterAngle"

.SS "\fBImVec2\fP ImGuiResizeBorderDef::SegmentN1"

.SS "\fBImVec2\fP ImGuiResizeBorderDef::SegmentN2"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
