.TH "ImGuiSelectionRequest" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiSelectionRequest
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imgui\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBImGuiSelectionRequestType\fP \fBType\fP"
.br
.ti -1c
.RI "bool \fBSelected\fP"
.br
.ti -1c
.RI "\fBImS8\fP \fBRangeDirection\fP"
.br
.ti -1c
.RI "\fBImGuiSelectionUserData\fP \fBRangeFirstItem\fP"
.br
.ti -1c
.RI "\fBImGuiSelectionUserData\fP \fBRangeLastItem\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBImS8\fP ImGuiSelectionRequest::RangeDirection"

.SS "\fBImGuiSelectionUserData\fP ImGuiSelectionRequest::RangeFirstItem"

.SS "\fBImGuiSelectionUserData\fP ImGuiSelectionRequest::RangeLastItem"

.SS "bool ImGuiSelectionRequest::Selected"

.SS "\fBImGuiSelectionRequestType\fP ImGuiSelectionRequest::Type"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
