.TH "ImGuiLastItemData" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiLastItemData
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imgui_internal\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImGuiLastItemData\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBImGuiID\fP \fBID\fP"
.br
.ti -1c
.RI "\fBImGuiItemFlags\fP \fBItemFlags\fP"
.br
.ti -1c
.RI "\fBImGuiItemStatusFlags\fP \fBStatusFlags\fP"
.br
.ti -1c
.RI "\fBImRect\fP \fBRect\fP"
.br
.ti -1c
.RI "\fBImRect\fP \fBNavRect\fP"
.br
.ti -1c
.RI "\fBImRect\fP \fBDisplayRect\fP"
.br
.ti -1c
.RI "\fBImRect\fP \fBClipRect\fP"
.br
.ti -1c
.RI "\fBImGuiKeyChord\fP \fBShortcut\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ImGuiLastItemData::ImGuiLastItemData ()\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBImRect\fP ImGuiLastItemData::ClipRect"

.SS "\fBImRect\fP ImGuiLastItemData::DisplayRect"

.SS "\fBImGuiID\fP ImGuiLastItemData::ID"

.SS "\fBImGuiItemFlags\fP ImGuiLastItemData::ItemFlags"

.SS "\fBImRect\fP ImGuiLastItemData::NavRect"

.SS "\fBImRect\fP ImGuiLastItemData::Rect"

.SS "\fBImGuiKeyChord\fP ImGuiLastItemData::Shortcut"

.SS "\fBImGuiItemStatusFlags\fP ImGuiLastItemData::StatusFlags"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
