.TH "ImGuiNextWindowData" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiNextWindowData
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imgui_internal\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImGuiNextWindowData\fP ()"
.br
.ti -1c
.RI "void \fBClearFlags\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBImGuiNextWindowDataFlags\fP \fBHasFlags\fP"
.br
.ti -1c
.RI "\fBImGuiCond\fP \fBPosCond\fP"
.br
.ti -1c
.RI "\fBImGuiCond\fP \fBSizeCond\fP"
.br
.ti -1c
.RI "\fBImGuiCond\fP \fBCollapsedCond\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBPosVal\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBPosPivotVal\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBSizeVal\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBContentSizeVal\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBScrollVal\fP"
.br
.ti -1c
.RI "\fBImGuiWindowFlags\fP \fBWindowFlags\fP"
.br
.ti -1c
.RI "\fBImGuiChildFlags\fP \fBChildFlags\fP"
.br
.ti -1c
.RI "bool \fBCollapsedVal\fP"
.br
.ti -1c
.RI "\fBImRect\fP \fBSizeConstraintRect\fP"
.br
.ti -1c
.RI "\fBImGuiSizeCallback\fP \fBSizeCallback\fP"
.br
.ti -1c
.RI "void * \fBSizeCallbackUserData\fP"
.br
.ti -1c
.RI "float \fBBgAlphaVal\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBMenuBarOffsetMinVal\fP"
.br
.ti -1c
.RI "\fBImGuiWindowRefreshFlags\fP \fBRefreshFlagsVal\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ImGuiNextWindowData::ImGuiNextWindowData ()\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void ImGuiNextWindowData::ClearFlags ()\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "float ImGuiNextWindowData::BgAlphaVal"

.SS "\fBImGuiChildFlags\fP ImGuiNextWindowData::ChildFlags"

.SS "\fBImGuiCond\fP ImGuiNextWindowData::CollapsedCond"

.SS "bool ImGuiNextWindowData::CollapsedVal"

.SS "\fBImVec2\fP ImGuiNextWindowData::ContentSizeVal"

.SS "\fBImGuiNextWindowDataFlags\fP ImGuiNextWindowData::HasFlags"

.SS "\fBImVec2\fP ImGuiNextWindowData::MenuBarOffsetMinVal"

.SS "\fBImGuiCond\fP ImGuiNextWindowData::PosCond"

.SS "\fBImVec2\fP ImGuiNextWindowData::PosPivotVal"

.SS "\fBImVec2\fP ImGuiNextWindowData::PosVal"

.SS "\fBImGuiWindowRefreshFlags\fP ImGuiNextWindowData::RefreshFlagsVal"

.SS "\fBImVec2\fP ImGuiNextWindowData::ScrollVal"

.SS "\fBImGuiSizeCallback\fP ImGuiNextWindowData::SizeCallback"

.SS "void* ImGuiNextWindowData::SizeCallbackUserData"

.SS "\fBImGuiCond\fP ImGuiNextWindowData::SizeCond"

.SS "\fBImRect\fP ImGuiNextWindowData::SizeConstraintRect"

.SS "\fBImVec2\fP ImGuiNextWindowData::SizeVal"

.SS "\fBImGuiWindowFlags\fP ImGuiNextWindowData::WindowFlags"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
