.TH "ImGuiOldColumns" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiOldColumns
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imgui_internal\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImGuiOldColumns\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBImGuiID\fP \fBID\fP"
.br
.ti -1c
.RI "\fBImGuiOldColumnFlags\fP \fBFlags\fP"
.br
.ti -1c
.RI "bool \fBIsFirstFrame\fP"
.br
.ti -1c
.RI "bool \fBIsBeingResized\fP"
.br
.ti -1c
.RI "int \fBCurrent\fP"
.br
.ti -1c
.RI "int \fBCount\fP"
.br
.ti -1c
.RI "float \fBOffMinX\fP"
.br
.ti -1c
.RI "float \fBOffMaxX\fP"
.br
.ti -1c
.RI "float \fBLineMinY\fP"
.br
.ti -1c
.RI "float \fBLineMaxY\fP"
.br
.ti -1c
.RI "float \fBHostCursorPosY\fP"
.br
.ti -1c
.RI "float \fBHostCursorMaxPosX\fP"
.br
.ti -1c
.RI "\fBImRect\fP \fBHostInitialClipRect\fP"
.br
.ti -1c
.RI "\fBImRect\fP \fBHostBackupClipRect\fP"
.br
.ti -1c
.RI "\fBImRect\fP \fBHostBackupParentWorkRect\fP"
.br
.ti -1c
.RI "\fBImVector\fP< \fBImGuiOldColumnData\fP > \fBColumns\fP"
.br
.ti -1c
.RI "\fBImDrawListSplitter\fP \fBSplitter\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ImGuiOldColumns::ImGuiOldColumns ()\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBImVector\fP<\fBImGuiOldColumnData\fP> ImGuiOldColumns::Columns"

.SS "int ImGuiOldColumns::Count"

.SS "int ImGuiOldColumns::Current"

.SS "\fBImGuiOldColumnFlags\fP ImGuiOldColumns::Flags"

.SS "\fBImRect\fP ImGuiOldColumns::HostBackupClipRect"

.SS "\fBImRect\fP ImGuiOldColumns::HostBackupParentWorkRect"

.SS "float ImGuiOldColumns::HostCursorMaxPosX"

.SS "float ImGuiOldColumns::HostCursorPosY"

.SS "\fBImRect\fP ImGuiOldColumns::HostInitialClipRect"

.SS "\fBImGuiID\fP ImGuiOldColumns::ID"

.SS "bool ImGuiOldColumns::IsBeingResized"

.SS "bool ImGuiOldColumns::IsFirstFrame"

.SS "float ImGuiOldColumns::LineMaxY"

.SS "float ImGuiOldColumns::LineMinY"

.SS "float ImGuiOldColumns::OffMaxX"

.SS "float ImGuiOldColumns::OffMinX"

.SS "\fBImDrawListSplitter\fP ImGuiOldColumns::Splitter"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
