.TH "ImGuiComboPreviewData" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiComboPreviewData
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imgui_internal\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImGuiComboPreviewData\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBImRect\fP \fBPreviewRect\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBBackupCursorPos\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBBackupCursorMaxPos\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBBackupCursorPosPrevLine\fP"
.br
.ti -1c
.RI "float \fBBackupPrevLineTextBaseOffset\fP"
.br
.ti -1c
.RI "\fBImGuiLayoutType\fP \fBBackupLayout\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ImGuiComboPreviewData::ImGuiComboPreviewData ()\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBImVec2\fP ImGuiComboPreviewData::BackupCursorMaxPos"

.SS "\fBImVec2\fP ImGuiComboPreviewData::BackupCursorPos"

.SS "\fBImVec2\fP ImGuiComboPreviewData::BackupCursorPosPrevLine"

.SS "\fBImGuiLayoutType\fP ImGuiComboPreviewData::BackupLayout"

.SS "float ImGuiComboPreviewData::BackupPrevLineTextBaseOffset"

.SS "\fBImRect\fP ImGuiComboPreviewData::PreviewRect"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
