.TH "ImGuiMultiSelectState" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiMultiSelectState
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imgui_internal\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImGuiMultiSelectState\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBImGuiWindow\fP * \fBWindow\fP"
.br
.ti -1c
.RI "\fBImGuiID\fP \fBID\fP"
.br
.ti -1c
.RI "int \fBLastFrameActive\fP"
.br
.ti -1c
.RI "int \fBLastSelectionSize\fP"
.br
.ti -1c
.RI "\fBImS8\fP \fBRangeSelected\fP"
.br
.ti -1c
.RI "\fBImS8\fP \fBNavIdSelected\fP"
.br
.ti -1c
.RI "\fBImGuiSelectionUserData\fP \fBRangeSrcItem\fP"
.br
.ti -1c
.RI "\fBImGuiSelectionUserData\fP \fBNavIdItem\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ImGuiMultiSelectState::ImGuiMultiSelectState ()\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBImGuiID\fP ImGuiMultiSelectState::ID"

.SS "int ImGuiMultiSelectState::LastFrameActive"

.SS "int ImGuiMultiSelectState::LastSelectionSize"

.SS "\fBImGuiSelectionUserData\fP ImGuiMultiSelectState::NavIdItem"

.SS "\fBImS8\fP ImGuiMultiSelectState::NavIdSelected"

.SS "\fBImS8\fP ImGuiMultiSelectState::RangeSelected"

.SS "\fBImGuiSelectionUserData\fP ImGuiMultiSelectState::RangeSrcItem"

.SS "\fBImGuiWindow\fP* ImGuiMultiSelectState::Window"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
