.TH "ImGuiDebugAllocInfo" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiDebugAllocInfo
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imgui_internal\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImGuiDebugAllocInfo\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBTotalAllocCount\fP"
.br
.ti -1c
.RI "int \fBTotalFreeCount\fP"
.br
.ti -1c
.RI "\fBImS16\fP \fBLastEntriesIdx\fP"
.br
.ti -1c
.RI "\fBImGuiDebugAllocEntry\fP \fBLastEntriesBuf\fP [6]"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ImGuiDebugAllocInfo::ImGuiDebugAllocInfo ()\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBImGuiDebugAllocEntry\fP ImGuiDebugAllocInfo::LastEntriesBuf[6]"

.SS "\fBImS16\fP ImGuiDebugAllocInfo::LastEntriesIdx"

.SS "int ImGuiDebugAllocInfo::TotalAllocCount"

.SS "int ImGuiDebugAllocInfo::TotalFreeCount"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
