.TH "ImGuiKeyRoutingTable" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiKeyRoutingTable
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imgui_internal\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImGuiKeyRoutingTable\fP ()"
.br
.ti -1c
.RI "void \fBClear\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBImGuiKeyRoutingIndex\fP \fBIndex\fP [\fBImGuiKey_NamedKey_COUNT\fP]"
.br
.ti -1c
.RI "\fBImVector\fP< \fBImGuiKeyRoutingData\fP > \fBEntries\fP"
.br
.ti -1c
.RI "\fBImVector\fP< \fBImGuiKeyRoutingData\fP > \fBEntriesNext\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ImGuiKeyRoutingTable::ImGuiKeyRoutingTable ()\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void ImGuiKeyRoutingTable::Clear ()\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBImVector\fP<\fBImGuiKeyRoutingData\fP> ImGuiKeyRoutingTable::Entries"

.SS "\fBImVector\fP<\fBImGuiKeyRoutingData\fP> ImGuiKeyRoutingTable::EntriesNext"

.SS "\fBImGuiKeyRoutingIndex\fP ImGuiKeyRoutingTable::Index[\fBImGuiKey_NamedKey_COUNT\fP]"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
