.TH "ImGuiErrorRecoveryState" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiErrorRecoveryState
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imgui_internal\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImGuiErrorRecoveryState\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "short \fBSizeOfWindowStack\fP"
.br
.ti -1c
.RI "short \fBSizeOfIDStack\fP"
.br
.ti -1c
.RI "short \fBSizeOfTreeStack\fP"
.br
.ti -1c
.RI "short \fBSizeOfColorStack\fP"
.br
.ti -1c
.RI "short \fBSizeOfStyleVarStack\fP"
.br
.ti -1c
.RI "short \fBSizeOfFontStack\fP"
.br
.ti -1c
.RI "short \fBSizeOfFocusScopeStack\fP"
.br
.ti -1c
.RI "short \fBSizeOfGroupStack\fP"
.br
.ti -1c
.RI "short \fBSizeOfItemFlagsStack\fP"
.br
.ti -1c
.RI "short \fBSizeOfBeginPopupStack\fP"
.br
.ti -1c
.RI "short \fBSizeOfDisabledStack\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ImGuiErrorRecoveryState::ImGuiErrorRecoveryState ()\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "short ImGuiErrorRecoveryState::SizeOfBeginPopupStack"

.SS "short ImGuiErrorRecoveryState::SizeOfColorStack"

.SS "short ImGuiErrorRecoveryState::SizeOfDisabledStack"

.SS "short ImGuiErrorRecoveryState::SizeOfFocusScopeStack"

.SS "short ImGuiErrorRecoveryState::SizeOfFontStack"

.SS "short ImGuiErrorRecoveryState::SizeOfGroupStack"

.SS "short ImGuiErrorRecoveryState::SizeOfIDStack"

.SS "short ImGuiErrorRecoveryState::SizeOfItemFlagsStack"

.SS "short ImGuiErrorRecoveryState::SizeOfStyleVarStack"

.SS "short ImGuiErrorRecoveryState::SizeOfTreeStack"

.SS "short ImGuiErrorRecoveryState::SizeOfWindowStack"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
