.TH "ImGuiInputEventAppFocused" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiInputEventAppFocused
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imgui_internal\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBFocused\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "bool ImGuiInputEventAppFocused::Focused"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
