.TH "ImGuiListClipperRange" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiListClipperRange
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imgui_internal\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBImGuiListClipperRange\fP \fBFromIndices\fP (int min, int max)"
.br
.ti -1c
.RI "static \fBImGuiListClipperRange\fP \fBFromPositions\fP (float y1, float y2, int off_min, int off_max)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBMin\fP"
.br
.ti -1c
.RI "int \fBMax\fP"
.br
.ti -1c
.RI "bool \fBPosToIndexConvert\fP"
.br
.ti -1c
.RI "\fBImS8\fP \fBPosToIndexOffsetMin\fP"
.br
.ti -1c
.RI "\fBImS8\fP \fBPosToIndexOffsetMax\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static \fBImGuiListClipperRange\fP ImGuiListClipperRange::FromIndices (int min, int max)\fR [inline]\fP, \fR [static]\fP"

.SS "static \fBImGuiListClipperRange\fP ImGuiListClipperRange::FromPositions (float y1, float y2, int off_min, int off_max)\fR [inline]\fP, \fR [static]\fP"

.SH "Member Data Documentation"
.PP 
.SS "int ImGuiListClipperRange::Max"

.SS "int ImGuiListClipperRange::Min"

.SS "bool ImGuiListClipperRange::PosToIndexConvert"

.SS "\fBImS8\fP ImGuiListClipperRange::PosToIndexOffsetMax"

.SS "\fBImS8\fP ImGuiListClipperRange::PosToIndexOffsetMin"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
