.TH "ImGuiDataTypeStorage" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiDataTypeStorage
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imgui_internal\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBImU8\fP \fBData\fP [8]"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBImU8\fP ImGuiDataTypeStorage::Data[8]"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
