.TH "ImGuiMultiSelectIO" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiMultiSelectIO
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imgui\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBImVector\fP< \fBImGuiSelectionRequest\fP > \fBRequests\fP"
.br
.ti -1c
.RI "\fBImGuiSelectionUserData\fP \fBRangeSrcItem\fP"
.br
.ti -1c
.RI "\fBImGuiSelectionUserData\fP \fBNavIdItem\fP"
.br
.ti -1c
.RI "bool \fBNavIdSelected\fP"
.br
.ti -1c
.RI "bool \fBRangeSrcReset\fP"
.br
.ti -1c
.RI "int \fBItemsCount\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int ImGuiMultiSelectIO::ItemsCount"

.SS "\fBImGuiSelectionUserData\fP ImGuiMultiSelectIO::NavIdItem"

.SS "bool ImGuiMultiSelectIO::NavIdSelected"

.SS "\fBImGuiSelectionUserData\fP ImGuiMultiSelectIO::RangeSrcItem"

.SS "bool ImGuiMultiSelectIO::RangeSrcReset"

.SS "\fBImVector\fP<\fBImGuiSelectionRequest\fP> ImGuiMultiSelectIO::Requests"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
