.TH "ImGuiResizeGripDef" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiResizeGripDef
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBImVec2\fP \fBCornerPosN\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBInnerDir\fP"
.br
.ti -1c
.RI "int \fBAngleMin12\fP"
.br
.ti -1c
.RI "int \fBAngleMax12\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int ImGuiResizeGripDef::AngleMax12"

.SS "int ImGuiResizeGripDef::AngleMin12"

.SS "\fBImVec2\fP ImGuiResizeGripDef::CornerPosN"

.SS "\fBImVec2\fP ImGuiResizeGripDef::InnerDir"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
