.TH "ImGuiTypingSelectState" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiTypingSelectState
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imgui_internal\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImGuiTypingSelectState\fP ()"
.br
.ti -1c
.RI "void \fBClear\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBImGuiTypingSelectRequest\fP \fBRequest\fP"
.br
.ti -1c
.RI "char \fBSearchBuffer\fP [64]"
.br
.ti -1c
.RI "\fBImGuiID\fP \fBFocusScope\fP"
.br
.ti -1c
.RI "int \fBLastRequestFrame\fP = 0"
.br
.ti -1c
.RI "float \fBLastRequestTime\fP = 0\&.0f"
.br
.ti -1c
.RI "bool \fBSingleCharModeLock\fP = false"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ImGuiTypingSelectState::ImGuiTypingSelectState ()\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void ImGuiTypingSelectState::Clear ()\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBImGuiID\fP ImGuiTypingSelectState::FocusScope"

.SS "int ImGuiTypingSelectState::LastRequestFrame = 0"

.SS "float ImGuiTypingSelectState::LastRequestTime = 0\&.0f"

.SS "\fBImGuiTypingSelectRequest\fP ImGuiTypingSelectState::Request"

.SS "char ImGuiTypingSelectState::SearchBuffer[64]"

.SS "bool ImGuiTypingSelectState::SingleCharModeLock = false"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
