.TH "ImGuiNextItemData" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiNextItemData
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imgui_internal\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImGuiNextItemData\fP ()"
.br
.ti -1c
.RI "void \fBClearFlags\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBImGuiNextItemDataFlags\fP \fBHasFlags\fP"
.br
.ti -1c
.RI "\fBImGuiItemFlags\fP \fBItemFlags\fP"
.br
.ti -1c
.RI "\fBImGuiID\fP \fBFocusScopeId\fP"
.br
.ti -1c
.RI "\fBImGuiSelectionUserData\fP \fBSelectionUserData\fP"
.br
.ti -1c
.RI "float \fBWidth\fP"
.br
.ti -1c
.RI "\fBImGuiKeyChord\fP \fBShortcut\fP"
.br
.ti -1c
.RI "\fBImGuiInputFlags\fP \fBShortcutFlags\fP"
.br
.ti -1c
.RI "bool \fBOpenVal\fP"
.br
.ti -1c
.RI "\fBImU8\fP \fBOpenCond\fP"
.br
.ti -1c
.RI "\fBImGuiDataTypeStorage\fP \fBRefVal\fP"
.br
.ti -1c
.RI "\fBImGuiID\fP \fBStorageId\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ImGuiNextItemData::ImGuiNextItemData ()\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void ImGuiNextItemData::ClearFlags ()\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBImGuiID\fP ImGuiNextItemData::FocusScopeId"

.SS "\fBImGuiNextItemDataFlags\fP ImGuiNextItemData::HasFlags"

.SS "\fBImGuiItemFlags\fP ImGuiNextItemData::ItemFlags"

.SS "\fBImU8\fP ImGuiNextItemData::OpenCond"

.SS "bool ImGuiNextItemData::OpenVal"

.SS "\fBImGuiDataTypeStorage\fP ImGuiNextItemData::RefVal"

.SS "\fBImGuiSelectionUserData\fP ImGuiNextItemData::SelectionUserData"

.SS "\fBImGuiKeyChord\fP ImGuiNextItemData::Shortcut"

.SS "\fBImGuiInputFlags\fP ImGuiNextItemData::ShortcutFlags"

.SS "\fBImGuiID\fP ImGuiNextItemData::StorageId"

.SS "float ImGuiNextItemData::Width"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
