.TH "ImGuiContextHook" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiContextHook
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imgui_internal\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImGuiContextHook\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBImGuiID\fP \fBHookId\fP"
.br
.ti -1c
.RI "\fBImGuiContextHookType\fP \fBType\fP"
.br
.ti -1c
.RI "\fBImGuiID\fP \fBOwner\fP"
.br
.ti -1c
.RI "\fBImGuiContextHookCallback\fP \fBCallback\fP"
.br
.ti -1c
.RI "void * \fBUserData\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ImGuiContextHook::ImGuiContextHook ()\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBImGuiContextHookCallback\fP ImGuiContextHook::Callback"

.SS "\fBImGuiID\fP ImGuiContextHook::HookId"

.SS "\fBImGuiID\fP ImGuiContextHook::Owner"

.SS "\fBImGuiContextHookType\fP ImGuiContextHook::Type"

.SS "void* ImGuiContextHook::UserData"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
