.TH "ImGuiOnceUponAFrame" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiOnceUponAFrame
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imgui\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImGuiOnceUponAFrame\fP ()"
.br
.ti -1c
.RI "\fBoperator bool\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBRefFrame\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ImGuiOnceUponAFrame::ImGuiOnceUponAFrame ()\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "ImGuiOnceUponAFrame::operator bool () const\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "int ImGuiOnceUponAFrame::RefFrame\fR [mutable]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
