.TH "ImGuiTabItem" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiTabItem
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imgui_internal\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImGuiTabItem\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBImGuiID\fP \fBID\fP"
.br
.ti -1c
.RI "\fBImGuiTabItemFlags\fP \fBFlags\fP"
.br
.ti -1c
.RI "int \fBLastFrameVisible\fP"
.br
.ti -1c
.RI "int \fBLastFrameSelected\fP"
.br
.ti -1c
.RI "float \fBOffset\fP"
.br
.ti -1c
.RI "float \fBWidth\fP"
.br
.ti -1c
.RI "float \fBContentWidth\fP"
.br
.ti -1c
.RI "float \fBRequestedWidth\fP"
.br
.ti -1c
.RI "\fBImS32\fP \fBNameOffset\fP"
.br
.ti -1c
.RI "\fBImS16\fP \fBBeginOrder\fP"
.br
.ti -1c
.RI "\fBImS16\fP \fBIndexDuringLayout\fP"
.br
.ti -1c
.RI "bool \fBWantClose\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ImGuiTabItem::ImGuiTabItem ()\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBImS16\fP ImGuiTabItem::BeginOrder"

.SS "float ImGuiTabItem::ContentWidth"

.SS "\fBImGuiTabItemFlags\fP ImGuiTabItem::Flags"

.SS "\fBImGuiID\fP ImGuiTabItem::ID"

.SS "\fBImS16\fP ImGuiTabItem::IndexDuringLayout"

.SS "int ImGuiTabItem::LastFrameSelected"

.SS "int ImGuiTabItem::LastFrameVisible"

.SS "\fBImS32\fP ImGuiTabItem::NameOffset"

.SS "float ImGuiTabItem::Offset"

.SS "float ImGuiTabItem::RequestedWidth"

.SS "bool ImGuiTabItem::WantClose"

.SS "float ImGuiTabItem::Width"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
