.TH "ImGuiTableInstanceData" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiTableInstanceData
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imgui_internal\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImGuiTableInstanceData\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBImGuiID\fP \fBTableInstanceID\fP"
.br
.ti -1c
.RI "float \fBLastOuterHeight\fP"
.br
.ti -1c
.RI "float \fBLastTopHeadersRowHeight\fP"
.br
.ti -1c
.RI "float \fBLastFrozenHeight\fP"
.br
.ti -1c
.RI "int \fBHoveredRowLast\fP"
.br
.ti -1c
.RI "int \fBHoveredRowNext\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ImGuiTableInstanceData::ImGuiTableInstanceData ()\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "int ImGuiTableInstanceData::HoveredRowLast"

.SS "int ImGuiTableInstanceData::HoveredRowNext"

.SS "float ImGuiTableInstanceData::LastFrozenHeight"

.SS "float ImGuiTableInstanceData::LastOuterHeight"

.SS "float ImGuiTableInstanceData::LastTopHeadersRowHeight"

.SS "\fBImGuiID\fP ImGuiTableInstanceData::TableInstanceID"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
