.TH "colossal_cpp/imgui/imgui_impl_opengl3.cpp" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
colossal_cpp/imgui/imgui_impl_opengl3.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'imgui\&.h'\fP
.br
\fR#include 'imgui_impl_opengl3\&.h'\fP
.br
\fR#include <stdio\&.h>\fP
.br
\fR#include <stdint\&.h>\fP
.br
\fR#include 'imgui_impl_opengl3_loader\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBImGui_ImplOpenGL3_Data\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBIMGL3W_IMPL\fP"
.br
.ti -1c
.RI "#define \fBIMGUI_IMPL_OPENGL_LOADER_IMGL3W\fP"
.br
.ti -1c
.RI "#define \fBIMGUI_IMPL_OPENGL_USE_VERTEX_ARRAY\fP"
.br
.ti -1c
.RI "#define \fBIMGUI_IMPL_OPENGL_HAS_EXTENSIONS\fP"
.br
.ti -1c
.RI "#define \fBIMGUI_IMPL_OPENGL_MAY_HAVE_POLYGON_MODE\fP"
.br
.ti -1c
.RI "#define \fBIMGUI_IMPL_OPENGL_MAY_HAVE_BIND_BUFFER_PIXEL_UNPACK\fP"
.br
.ti -1c
.RI "#define \fBGL_CALL\fP(_CALL)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBImGui_ImplOpenGL3_InitLoader\fP ()"
.br
.ti -1c
.RI "bool \fBImGui_ImplOpenGL3_Init\fP (const char *glsl_version)"
.br
.ti -1c
.RI "void \fBImGui_ImplOpenGL3_Shutdown\fP ()"
.br
.ti -1c
.RI "void \fBImGui_ImplOpenGL3_NewFrame\fP ()"
.br
.ti -1c
.RI "void \fBImGui_ImplOpenGL3_RenderDrawData\fP (\fBImDrawData\fP *draw_data)"
.br
.ti -1c
.RI "bool \fBImGui_ImplOpenGL3_CreateFontsTexture\fP ()"
.br
.ti -1c
.RI "void \fBImGui_ImplOpenGL3_DestroyFontsTexture\fP ()"
.br
.ti -1c
.RI "bool \fBImGui_ImplOpenGL3_CreateDeviceObjects\fP ()"
.br
.ti -1c
.RI "void \fBImGui_ImplOpenGL3_DestroyDeviceObjects\fP ()"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define GL_CALL( _CALL)"
\fBValue:\fP
.nf
_CALL
.PP
.fi

.SS "#define IMGL3W_IMPL"

.SS "#define IMGUI_IMPL_OPENGL_HAS_EXTENSIONS"

.SS "#define IMGUI_IMPL_OPENGL_LOADER_IMGL3W"

.SS "#define IMGUI_IMPL_OPENGL_MAY_HAVE_BIND_BUFFER_PIXEL_UNPACK"

.SS "#define IMGUI_IMPL_OPENGL_MAY_HAVE_POLYGON_MODE"

.SS "#define IMGUI_IMPL_OPENGL_USE_VERTEX_ARRAY"

.SH "Function Documentation"
.PP 
.SS "bool ImGui_ImplOpenGL3_CreateDeviceObjects ()"

.SS "bool ImGui_ImplOpenGL3_CreateFontsTexture ()"

.SS "void ImGui_ImplOpenGL3_DestroyDeviceObjects ()"

.SS "void ImGui_ImplOpenGL3_DestroyFontsTexture ()"

.SS "bool ImGui_ImplOpenGL3_Init (const char * glsl_version)"

.SS "bool ImGui_ImplOpenGL3_InitLoader ()"

.SS "void ImGui_ImplOpenGL3_NewFrame ()"

.SS "void ImGui_ImplOpenGL3_RenderDrawData (\fBImDrawData\fP * draw_data)"

.SS "void ImGui_ImplOpenGL3_Shutdown ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
