.TH "ImStb::StbUndoState" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImStb::StbUndoState
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBStbUndoRecord\fP \fBundo_rec\fP [\fBIMSTB_TEXTEDIT_UNDOSTATECOUNT\fP]"
.br
.ti -1c
.RI "\fBIMSTB_TEXTEDIT_CHARTYPE\fP \fBundo_char\fP [\fBIMSTB_TEXTEDIT_UNDOCHARCOUNT\fP]"
.br
.ti -1c
.RI "short \fBundo_point\fP"
.br
.ti -1c
.RI "short \fBredo_point\fP"
.br
.ti -1c
.RI "int \fBundo_char_point\fP"
.br
.ti -1c
.RI "int \fBredo_char_point\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int ImStb::StbUndoState::redo_char_point"

.SS "short ImStb::StbUndoState::redo_point"

.SS "\fBIMSTB_TEXTEDIT_CHARTYPE\fP ImStb::StbUndoState::undo_char[\fBIMSTB_TEXTEDIT_UNDOCHARCOUNT\fP]"

.SS "int ImStb::StbUndoState::undo_char_point"

.SS "short ImStb::StbUndoState::undo_point"

.SS "\fBStbUndoRecord\fP ImStb::StbUndoState::undo_rec[\fBIMSTB_TEXTEDIT_UNDOSTATECOUNT\fP]"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
