.TH "ImStb" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImStb
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBSTB_TexteditState\fP"
.br
.ti -1c
.RI "struct \fBStbFindState\fP"
.br
.ti -1c
.RI "struct \fBStbTexteditRow\fP"
.br
.ti -1c
.RI "struct \fBStbUndoRecord\fP"
.br
.ti -1c
.RI "struct \fBStbUndoState\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct ImStb::STB_TexteditState \fBSTB_TexteditState\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct ImStb::STB_TexteditState ImStb::STB_TexteditState"

.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
