.TH "ImStb::STB_TexteditState" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImStb::STB_TexteditState
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBcursor\fP"
.br
.ti -1c
.RI "int \fBselect_start\fP"
.br
.ti -1c
.RI "int \fBselect_end\fP"
.br
.ti -1c
.RI "unsigned char \fBinsert_mode\fP"
.br
.ti -1c
.RI "int \fBrow_count_per_page\fP"
.br
.ti -1c
.RI "unsigned char \fBcursor_at_end_of_line\fP"
.br
.ti -1c
.RI "unsigned char \fBinitialized\fP"
.br
.ti -1c
.RI "unsigned char \fBhas_preferred_x\fP"
.br
.ti -1c
.RI "unsigned char \fBsingle_line\fP"
.br
.ti -1c
.RI "unsigned char \fBpadding1\fP"
.br
.ti -1c
.RI "unsigned char \fBpadding2\fP"
.br
.ti -1c
.RI "unsigned char \fBpadding3\fP"
.br
.ti -1c
.RI "float \fBpreferred_x\fP"
.br
.ti -1c
.RI "\fBStbUndoState\fP \fBundostate\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int ImStb::STB_TexteditState::cursor"

.SS "unsigned char ImStb::STB_TexteditState::cursor_at_end_of_line"

.SS "unsigned char ImStb::STB_TexteditState::has_preferred_x"

.SS "unsigned char ImStb::STB_TexteditState::initialized"

.SS "unsigned char ImStb::STB_TexteditState::insert_mode"

.SS "unsigned char ImStb::STB_TexteditState::padding1"

.SS "unsigned char ImStb::STB_TexteditState::padding2"

.SS "unsigned char ImStb::STB_TexteditState::padding3"

.SS "float ImStb::STB_TexteditState::preferred_x"

.SS "int ImStb::STB_TexteditState::row_count_per_page"

.SS "int ImStb::STB_TexteditState::select_end"

.SS "int ImStb::STB_TexteditState::select_start"

.SS "unsigned char ImStb::STB_TexteditState::single_line"

.SS "\fBStbUndoState\fP ImStb::STB_TexteditState::undostate"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
