.TH "ImStb::StbFindState" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImStb::StbFindState
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBx\fP"
.br
.ti -1c
.RI "float \fBy\fP"
.br
.ti -1c
.RI "float \fBheight\fP"
.br
.ti -1c
.RI "int \fBfirst_char\fP"
.br
.ti -1c
.RI "int \fBlength\fP"
.br
.ti -1c
.RI "int \fBprev_first\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int ImStb::StbFindState::first_char"

.SS "float ImStb::StbFindState::height"

.SS "int ImStb::StbFindState::length"

.SS "int ImStb::StbFindState::prev_first"

.SS "float ImStb::StbFindState::x"

.SS "float ImStb::StbFindState::y"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
