.TH "ImStb::StbUndoRecord" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImStb::StbUndoRecord
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBIMSTB_TEXTEDIT_POSITIONTYPE\fP \fBwhere\fP"
.br
.ti -1c
.RI "\fBIMSTB_TEXTEDIT_POSITIONTYPE\fP \fBinsert_length\fP"
.br
.ti -1c
.RI "\fBIMSTB_TEXTEDIT_POSITIONTYPE\fP \fBdelete_length\fP"
.br
.ti -1c
.RI "int \fBchar_storage\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int ImStb::StbUndoRecord::char_storage"

.SS "\fBIMSTB_TEXTEDIT_POSITIONTYPE\fP ImStb::StbUndoRecord::delete_length"

.SS "\fBIMSTB_TEXTEDIT_POSITIONTYPE\fP ImStb::StbUndoRecord::insert_length"

.SS "\fBIMSTB_TEXTEDIT_POSITIONTYPE\fP ImStb::StbUndoRecord::where"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
