.TH "ImStb::StbTexteditRow" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImStb::StbTexteditRow
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBx0\fP"
.br
.ti -1c
.RI "float \fBx1\fP"
.br
.ti -1c
.RI "float \fBbaseline_y_delta\fP"
.br
.ti -1c
.RI "float \fBymin\fP"
.br
.ti -1c
.RI "float \fBymax\fP"
.br
.ti -1c
.RI "int \fBnum_chars\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "float ImStb::StbTexteditRow::baseline_y_delta"

.SS "int ImStb::StbTexteditRow::num_chars"

.SS "float ImStb::StbTexteditRow::x0"

.SS "float ImStb::StbTexteditRow::x1"

.SS "float ImStb::StbTexteditRow::ymax"

.SS "float ImStb::StbTexteditRow::ymin"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
