.TH "colossal_cpp/imgui/imstb_textedit.h" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
colossal_cpp/imgui/imstb_textedit.h
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBStbUndoRecord\fP"
.br
.ti -1c
.RI "struct \fBStbUndoState\fP"
.br
.ti -1c
.RI "struct \fBSTB_TexteditState\fP"
.br
.ti -1c
.RI "struct \fBStbTexteditRow\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBIMSTB_TEXTEDIT_UNDOSTATECOUNT\fP   99"
.br
.ti -1c
.RI "#define \fBIMSTB_TEXTEDIT_UNDOCHARCOUNT\fP   999"
.br
.ti -1c
.RI "#define \fBIMSTB_TEXTEDIT_CHARTYPE\fP   int"
.br
.ti -1c
.RI "#define \fBIMSTB_TEXTEDIT_POSITIONTYPE\fP   int"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct STB_TexteditState \fBSTB_TexteditState\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define IMSTB_TEXTEDIT_CHARTYPE   int"

.SS "#define IMSTB_TEXTEDIT_POSITIONTYPE   int"

.SS "#define IMSTB_TEXTEDIT_UNDOCHARCOUNT   999"

.SS "#define IMSTB_TEXTEDIT_UNDOSTATECOUNT   99"

.SH "Typedef Documentation"
.PP 
.SS "typedef struct STB_TexteditState STB_TexteditState"

.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
