.TH "ImTriangulatorNode" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImTriangulatorNode
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBUnlink\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBImTriangulatorNodeType\fP \fBType\fP"
.br
.ti -1c
.RI "int \fBIndex\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBPos\fP"
.br
.ti -1c
.RI "\fBImTriangulatorNode\fP * \fBNext\fP"
.br
.ti -1c
.RI "\fBImTriangulatorNode\fP * \fBPrev\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void ImTriangulatorNode::Unlink ()\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "int ImTriangulatorNode::Index"

.SS "\fBImTriangulatorNode\fP* ImTriangulatorNode::Next"

.SS "\fBImVec2\fP ImTriangulatorNode::Pos"

.SS "\fBImTriangulatorNode\fP* ImTriangulatorNode::Prev"

.SS "\fBImTriangulatorNodeType\fP ImTriangulatorNode::Type"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
