.TH "ImTriangulatorNodeSpan" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImTriangulatorNodeSpan
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBpush_back\fP (\fBImTriangulatorNode\fP *node)"
.br
.ti -1c
.RI "void \fBfind_erase_unsorted\fP (int idx)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBImTriangulatorNode\fP ** \fBData\fP = NULL"
.br
.ti -1c
.RI "int \fBSize\fP = 0"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void ImTriangulatorNodeSpan::find_erase_unsorted (int idx)\fR [inline]\fP"

.SS "void ImTriangulatorNodeSpan::push_back (\fBImTriangulatorNode\fP * node)\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBImTriangulatorNode\fP** ImTriangulatorNodeSpan::Data = NULL"

.SS "int ImTriangulatorNodeSpan::Size = 0"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
