.TH "ImVec1" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImVec1
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imgui_internal\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "constexpr \fBImVec1\fP ()"
.br
.ti -1c
.RI "constexpr \fBImVec1\fP (float _x)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBx\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ImVec1::ImVec1 ()\fR [inline]\fP, \fR [constexpr]\fP"

.SS "ImVec1::ImVec1 (float _x)\fR [inline]\fP, \fR [constexpr]\fP"

.SH "Member Data Documentation"
.PP 
.SS "float ImVec1::x"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
