.TH "ImVec2" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImVec2
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imgui\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "constexpr \fBImVec2\fP ()"
.br
.ti -1c
.RI "constexpr \fBImVec2\fP (float _x, float _y)"
.br
.ti -1c
.RI "float & \fBoperator[]\fP (size_t idx)"
.br
.ti -1c
.RI "float \fBoperator[]\fP (size_t idx) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBx\fP"
.br
.ti -1c
.RI "float \fBy\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ImVec2::ImVec2 ()\fR [inline]\fP, \fR [constexpr]\fP"

.SS "ImVec2::ImVec2 (float _x, float _y)\fR [inline]\fP, \fR [constexpr]\fP"

.SH "Member Function Documentation"
.PP 
.SS "float & ImVec2::operator[] (size_t idx)\fR [inline]\fP"

.SS "float ImVec2::operator[] (size_t idx) const\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "float ImVec2::x"

.SS "float ImVec2::y"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
