.TH "ImVec2ih" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImVec2ih
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imgui_internal\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "constexpr \fBImVec2ih\fP ()"
.br
.ti -1c
.RI "constexpr \fBImVec2ih\fP (short _x, short _y)"
.br
.ti -1c
.RI "constexpr \fBImVec2ih\fP (const \fBImVec2\fP &rhs)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "short \fBx\fP"
.br
.ti -1c
.RI "short \fBy\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ImVec2ih::ImVec2ih ()\fR [inline]\fP, \fR [constexpr]\fP"

.SS "ImVec2ih::ImVec2ih (short _x, short _y)\fR [inline]\fP, \fR [constexpr]\fP"

.SS "ImVec2ih::ImVec2ih (const \fBImVec2\fP & rhs)\fR [inline]\fP, \fR [explicit]\fP, \fR [constexpr]\fP"

.SH "Member Data Documentation"
.PP 
.SS "short ImVec2ih::x"

.SS "short ImVec2ih::y"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
