.TH "ImVec4" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImVec4
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imgui\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "constexpr \fBImVec4\fP ()"
.br
.ti -1c
.RI "constexpr \fBImVec4\fP (float _x, float _y, float _z, float _w)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBx\fP"
.br
.ti -1c
.RI "float \fBy\fP"
.br
.ti -1c
.RI "float \fBz\fP"
.br
.ti -1c
.RI "float \fBw\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ImVec4::ImVec4 ()\fR [inline]\fP, \fR [constexpr]\fP"

.SS "ImVec4::ImVec4 (float _x, float _y, float _z, float _w)\fR [inline]\fP, \fR [constexpr]\fP"

.SH "Member Data Documentation"
.PP 
.SS "float ImVec4::w"

.SS "float ImVec4::x"

.SS "float ImVec4::y"

.SS "float ImVec4::z"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
