.TH "colossal_cpp/mb_device.c" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
colossal_cpp/mb_device.c
.SH SYNOPSIS
.br
.PP
\fR#include 'mb_device\&.h'\fP
.br
\fR#include <stdlib\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBcl_mb_device\fP * \fBcl_device_init\fP (char const *name, size_t n_channels)"
.br
.ti -1c
.RI "int \fBcl_device_destroy\fP (\fBcl_mb_device\fP *device)"
.br
.RI "Clear the device and free its memory including channel memory\&. "
.in -1c
.SH "Detailed Description"
.PP 
Initialize the Modbus device\&. 
.SH "Function Documentation"
.PP 
.SS "int cl_device_destroy (\fBcl_mb_device\fP * device)"

.PP
Clear the device and free its memory including channel memory\&. 
.SS "\fBcl_mb_device\fP * cl_device_init (char const * name, size_t n_channels)"

.PP
\fBParameters\fP
.RS 4
\fIn_channels\fP Initial number of channels in the device\&. The functions should allocate enough space for all the channel data\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
