.TH "stbrp_context" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stbrp_context
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imstb_rectpack\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBwidth\fP"
.br
.ti -1c
.RI "int \fBheight\fP"
.br
.ti -1c
.RI "int \fBalign\fP"
.br
.ti -1c
.RI "int \fBinit_mode\fP"
.br
.ti -1c
.RI "int \fBheuristic\fP"
.br
.ti -1c
.RI "int \fBnum_nodes\fP"
.br
.ti -1c
.RI "\fBstbrp_node\fP * \fBactive_head\fP"
.br
.ti -1c
.RI "\fBstbrp_node\fP * \fBfree_head\fP"
.br
.ti -1c
.RI "\fBstbrp_node\fP \fBextra\fP [2]"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBstbrp_node\fP* stbrp_context::active_head"

.SS "int stbrp_context::align"

.SS "\fBstbrp_node\fP stbrp_context::extra[2]"

.SS "\fBstbrp_node\fP* stbrp_context::free_head"

.SS "int stbrp_context::height"

.SS "int stbrp_context::heuristic"

.SS "int stbrp_context::init_mode"

.SS "int stbrp_context::num_nodes"

.SS "int stbrp_context::width"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
