.TH "stbrp_rect" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stbrp_rect
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imstb_rectpack\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "\fBstbrp_coord\fP \fBw\fP"
.br
.ti -1c
.RI "\fBstbrp_coord\fP \fBh\fP"
.br
.ti -1c
.RI "\fBstbrp_coord\fP \fBx\fP"
.br
.ti -1c
.RI "\fBstbrp_coord\fP \fBy\fP"
.br
.ti -1c
.RI "int \fBwas_packed\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBstbrp_coord\fP stbrp_rect::h"

.SS "int stbrp_rect::id"

.SS "\fBstbrp_coord\fP stbrp_rect::w"

.SS "int stbrp_rect::was_packed"

.SS "\fBstbrp_coord\fP stbrp_rect::x"

.SS "\fBstbrp_coord\fP stbrp_rect::y"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
