.TH "stbrp_node" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stbrp_node
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imstb_rectpack\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBstbrp_coord\fP \fBx\fP"
.br
.ti -1c
.RI "\fBstbrp_coord\fP \fBy\fP"
.br
.ti -1c
.RI "\fBstbrp_node\fP * \fBnext\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBstbrp_node\fP* stbrp_node::next"

.SS "\fBstbrp_coord\fP stbrp_node::x"

.SS "\fBstbrp_coord\fP stbrp_node::y"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
