.TH "stbtt__bitmap" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stbtt__bitmap
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imstb_truetype\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBw\fP"
.br
.ti -1c
.RI "int \fBh\fP"
.br
.ti -1c
.RI "int \fBstride\fP"
.br
.ti -1c
.RI "unsigned char * \fBpixels\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int stbtt__bitmap::h"

.SS "unsigned char* stbtt__bitmap::pixels"

.SS "int stbtt__bitmap::stride"

.SS "int stbtt__bitmap::w"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
