.TH "stbtt_packedchar" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stbtt_packedchar
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imstb_truetype\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned short \fBx0\fP"
.br
.ti -1c
.RI "unsigned short \fBy0\fP"
.br
.ti -1c
.RI "unsigned short \fBx1\fP"
.br
.ti -1c
.RI "unsigned short \fBy1\fP"
.br
.ti -1c
.RI "float \fBxoff\fP"
.br
.ti -1c
.RI "float \fByoff\fP"
.br
.ti -1c
.RI "float \fBxadvance\fP"
.br
.ti -1c
.RI "float \fBxoff2\fP"
.br
.ti -1c
.RI "float \fByoff2\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "unsigned short stbtt_packedchar::x0"

.SS "unsigned short stbtt_packedchar::x1"

.SS "float stbtt_packedchar::xadvance"

.SS "float stbtt_packedchar::xoff"

.SS "float stbtt_packedchar::xoff2"

.SS "unsigned short stbtt_packedchar::y0"

.SS "unsigned short stbtt_packedchar::y1"

.SS "float stbtt_packedchar::yoff"

.SS "float stbtt_packedchar::yoff2"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
