.TH "stbtt_pack_range" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stbtt_pack_range
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imstb_truetype\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBfont_size\fP"
.br
.ti -1c
.RI "int \fBfirst_unicode_codepoint_in_range\fP"
.br
.ti -1c
.RI "int * \fBarray_of_unicode_codepoints\fP"
.br
.ti -1c
.RI "int \fBnum_chars\fP"
.br
.ti -1c
.RI "\fBstbtt_packedchar\fP * \fBchardata_for_range\fP"
.br
.ti -1c
.RI "unsigned char \fBh_oversample\fP"
.br
.ti -1c
.RI "unsigned char \fBv_oversample\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int* stbtt_pack_range::array_of_unicode_codepoints"

.SS "\fBstbtt_packedchar\fP* stbtt_pack_range::chardata_for_range"

.SS "int stbtt_pack_range::first_unicode_codepoint_in_range"

.SS "float stbtt_pack_range::font_size"

.SS "unsigned char stbtt_pack_range::h_oversample"

.SS "int stbtt_pack_range::num_chars"

.SS "unsigned char stbtt_pack_range::v_oversample"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
