.TH "stbtt_vertex" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stbtt_vertex
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imstb_truetype\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBstbtt_vertex_type\fP \fBx\fP"
.br
.ti -1c
.RI "\fBstbtt_vertex_type\fP \fBy\fP"
.br
.ti -1c
.RI "\fBstbtt_vertex_type\fP \fBcx\fP"
.br
.ti -1c
.RI "\fBstbtt_vertex_type\fP \fBcy\fP"
.br
.ti -1c
.RI "\fBstbtt_vertex_type\fP \fBcx1\fP"
.br
.ti -1c
.RI "\fBstbtt_vertex_type\fP \fBcy1\fP"
.br
.ti -1c
.RI "unsigned char \fBtype\fP"
.br
.ti -1c
.RI "unsigned char \fBpadding\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBstbtt_vertex_type\fP stbtt_vertex::cx"

.SS "\fBstbtt_vertex_type\fP stbtt_vertex::cx1"

.SS "\fBstbtt_vertex_type\fP stbtt_vertex::cy"

.SS "\fBstbtt_vertex_type\fP stbtt_vertex::cy1"

.SS "unsigned char stbtt_vertex::padding"

.SS "unsigned char stbtt_vertex::type"

.SS "\fBstbtt_vertex_type\fP stbtt_vertex::x"

.SS "\fBstbtt_vertex_type\fP stbtt_vertex::y"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
