.TH "StbTexteditRow" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StbTexteditRow
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imstb_textedit\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBx0\fP"
.br
.ti -1c
.RI "float \fBx1\fP"
.br
.ti -1c
.RI "float \fBbaseline_y_delta\fP"
.br
.ti -1c
.RI "float \fBymin\fP"
.br
.ti -1c
.RI "float \fBymax\fP"
.br
.ti -1c
.RI "int \fBnum_chars\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "float StbTexteditRow::baseline_y_delta"

.SS "int StbTexteditRow::num_chars"

.SS "float StbTexteditRow::x0"

.SS "float StbTexteditRow::x1"

.SS "float StbTexteditRow::ymax"

.SS "float StbTexteditRow::ymin"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
