.TH "stbtt_fontinfo" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stbtt_fontinfo
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imstb_truetype\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void * \fBuserdata\fP"
.br
.ti -1c
.RI "unsigned char * \fBdata\fP"
.br
.ti -1c
.RI "int \fBfontstart\fP"
.br
.ti -1c
.RI "int \fBnumGlyphs\fP"
.br
.ti -1c
.RI "int \fBloca\fP"
.br
.ti -1c
.RI "int \fBhead\fP"
.br
.ti -1c
.RI "int \fBglyf\fP"
.br
.ti -1c
.RI "int \fBhhea\fP"
.br
.ti -1c
.RI "int \fBhmtx\fP"
.br
.ti -1c
.RI "int \fBkern\fP"
.br
.ti -1c
.RI "int \fBgpos\fP"
.br
.ti -1c
.RI "int \fBsvg\fP"
.br
.ti -1c
.RI "int \fBindex_map\fP"
.br
.ti -1c
.RI "int \fBindexToLocFormat\fP"
.br
.ti -1c
.RI "\fBstbtt__buf\fP \fBcff\fP"
.br
.ti -1c
.RI "\fBstbtt__buf\fP \fBcharstrings\fP"
.br
.ti -1c
.RI "\fBstbtt__buf\fP \fBgsubrs\fP"
.br
.ti -1c
.RI "\fBstbtt__buf\fP \fBsubrs\fP"
.br
.ti -1c
.RI "\fBstbtt__buf\fP \fBfontdicts\fP"
.br
.ti -1c
.RI "\fBstbtt__buf\fP \fBfdselect\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBstbtt__buf\fP stbtt_fontinfo::cff"

.SS "\fBstbtt__buf\fP stbtt_fontinfo::charstrings"

.SS "unsigned char* stbtt_fontinfo::data"

.SS "\fBstbtt__buf\fP stbtt_fontinfo::fdselect"

.SS "\fBstbtt__buf\fP stbtt_fontinfo::fontdicts"

.SS "int stbtt_fontinfo::fontstart"

.SS "int stbtt_fontinfo::glyf"

.SS "int stbtt_fontinfo::gpos"

.SS "\fBstbtt__buf\fP stbtt_fontinfo::gsubrs"

.SS "int stbtt_fontinfo::head"

.SS "int stbtt_fontinfo::hhea"

.SS "int stbtt_fontinfo::hmtx"

.SS "int stbtt_fontinfo::index_map"

.SS "int stbtt_fontinfo::indexToLocFormat"

.SS "int stbtt_fontinfo::kern"

.SS "int stbtt_fontinfo::loca"

.SS "int stbtt_fontinfo::numGlyphs"

.SS "\fBstbtt__buf\fP stbtt_fontinfo::subrs"

.SS "int stbtt_fontinfo::svg"

.SS "void* stbtt_fontinfo::userdata"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
