.TH "stbtt_kerningentry" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stbtt_kerningentry
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imstb_truetype\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBglyph1\fP"
.br
.ti -1c
.RI "int \fBglyph2\fP"
.br
.ti -1c
.RI "int \fBadvance\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int stbtt_kerningentry::advance"

.SS "int stbtt_kerningentry::glyph1"

.SS "int stbtt_kerningentry::glyph2"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
