.TH "stbtt_pack_context" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stbtt_pack_context
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imstb_truetype\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void * \fBuser_allocator_context\fP"
.br
.ti -1c
.RI "void * \fBpack_info\fP"
.br
.ti -1c
.RI "int \fBwidth\fP"
.br
.ti -1c
.RI "int \fBheight\fP"
.br
.ti -1c
.RI "int \fBstride_in_bytes\fP"
.br
.ti -1c
.RI "int \fBpadding\fP"
.br
.ti -1c
.RI "int \fBskip_missing\fP"
.br
.ti -1c
.RI "unsigned int \fBh_oversample\fP"
.br
.ti -1c
.RI "unsigned int \fBv_oversample\fP"
.br
.ti -1c
.RI "unsigned char * \fBpixels\fP"
.br
.ti -1c
.RI "void * \fBnodes\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "unsigned int stbtt_pack_context::h_oversample"

.SS "int stbtt_pack_context::height"

.SS "void* stbtt_pack_context::nodes"

.SS "void* stbtt_pack_context::pack_info"

.SS "int stbtt_pack_context::padding"

.SS "unsigned char* stbtt_pack_context::pixels"

.SS "int stbtt_pack_context::skip_missing"

.SS "int stbtt_pack_context::stride_in_bytes"

.SS "void* stbtt_pack_context::user_allocator_context"

.SS "unsigned int stbtt_pack_context::v_oversample"

.SS "int stbtt_pack_context::width"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
