.TH "stbtt_aligned_quad" 3 "Version 0.1.0" "Colossal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stbtt_aligned_quad
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <imstb_truetype\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBx0\fP"
.br
.ti -1c
.RI "float \fBy0\fP"
.br
.ti -1c
.RI "float \fBs0\fP"
.br
.ti -1c
.RI "float \fBt0\fP"
.br
.ti -1c
.RI "float \fBx1\fP"
.br
.ti -1c
.RI "float \fBy1\fP"
.br
.ti -1c
.RI "float \fBs1\fP"
.br
.ti -1c
.RI "float \fBt1\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "float stbtt_aligned_quad::s0"

.SS "float stbtt_aligned_quad::s1"

.SS "float stbtt_aligned_quad::t0"

.SS "float stbtt_aligned_quad::t1"

.SS "float stbtt_aligned_quad::x0"

.SS "float stbtt_aligned_quad::x1"

.SS "float stbtt_aligned_quad::y0"

.SS "float stbtt_aligned_quad::y1"


.SH "Author"
.PP 
Generated automatically by Doxygen for Colossal from the source code\&.
